cloudformation_templates/aws_digitalmarketplace_admin_frontend.json
cloudformation_templates/aws_digitalmarketplace_search_api.json
cloudformation_templates/aws_elasticsearch.json
playbooks/roles/aws_digitalmarketplace_admin_frontend/defaults/main.yml
playbooks/roles/aws_digitalmarketplace_admin_frontend/tasks/main.yml
playbooks/roles/aws_digitalmarketplace_search_api/defaults/main.yml
playbooks/roles/aws_digitalmarketplace_search_api/tasks/main.yml
playbooks/roles/aws_elasticsearch/tasks/main.yml
playbooks/roles/elasticsearch/defaults/main.yml
playbooks/setup.yml
playbooks/teardown.yml
playbooks/vars/development.yml
user.yml.sample

Includes change to internal Elasticsearch ELB and elasticsearch-1.4

Admin and search CloudFormation stacks

---

cloudformation_templates/aws_digitalmarketplace_admin_frontend.json
cloudformation_templates/aws_digitalmarketplace_search_api.json
cloudformation_templates/aws_documents_s3.json
stacks.yml
user.yml.sample

Fixes environment variable names, adds S3 bucket for documents and admin password hash

Update admin frontend template

---

dmaws/cli.py

It got missed in the previous PR. We need tests in this repo.

Import os package in cli

---

setup.py

We use requirements.txt in all other repositories and it's a well
understood format.

Pull requirements from requirements.txt

---

cloudformation_templates/app_base.j2

Release notes for the 2015.03 Amazon Linux AMI:
http://aws.amazon.com/amazon-linux-ami/2015.03-release-notes/
Applied to all preview apps.

Update the EB solution stack to 2015.03 v1.3.0

---

cloudformation_templates/aws_cloudfront_www.json

The distribution was renamed

---

stacks.yml

DM_ENVIRONMENT is used by python apps to choose the config environment.

Set DM_ENVIRONMENT env var to stage for all EB apps

---

vars/production.yml
vars/staging.yml

This is a self signed certificate we're going to use until we're ready
to put production live.

Configure production to use *.beta.digital.. cert

---

cloudformation_templates/aws_rds_database.json
vars/development.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

Even though it uses that term throughout it's documentation.

CloudFormation doesn't understand Boolean

---

stacks.yml
vars/common.yml
vars/development.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

[example.com](example.com) expects this kind of thing.

Send dev monitoring emails to a dummy address

---

scripts/single-update-git.sh
scripts/update-git.sh

This is largely copied from github.gds/gds/development

Add scripts to update dm repos

---

scripts/get-instances.py

This is a quick and dirty script to list out instances from an
environment.

Add a script to list instances

---

playbooks/roles/nginx/tasks/main.yml
vars/common.yml

It's /etc/nginx, not /src/nginx

Fix nginx sites paths

---

vars/staging.yml

See: 412cf280153e63564203cb255d2d30c7821f993d

Change root domain to remove beta

---

stacks.yml

- requires https://github.gds/gds/digitalmarketplace-credentials/pull/20
- puts new email api key and secret key into admin app for sending invite emails

Adding properties to admin app for email sending

---

cloudformation_templates/aws_nginx.json
playbooks/roles/cloudwatch/templates/nginx_awslogs.conf.j2
playbooks/roles/nginx/templates/nginx.conf.j2
stacks.yml

Adds nginx logs to the json stream group using a log format similar
to the one used by Apache logs.

Add JSON stream for nginx log

---

playbooks/roles/nginx/templates/nginx.conf.j2
vars/common.yml

Add $request_time to access logs.
http://nginx.org/en/docs/http/ngx_http_log_module.html

Add request times to nginx logs

---

playbooks/roles/nginx/templates/nginx.conf.j2
vars/common.yml

Add HTTP Host header to nginx access log

Add HTTP Host header to nginx access log

---

vars/common.yml

This is the change committed in
https://github.com/alphagov/digitalmarketplace-aws/pull/144

Update nginx AMI

---

stacks.yml

These are the new bucket names agreed in the discussion about URLs
```
communications - framework documents and communications
documents      - publicly visible service documents
submissions    - draft service documents
agreements     - framework agreements
```

Add new bucket names

---

dmaws/commands/release.py

Fix bug in release command

---

vars/common.yml

I forgot to add it to the pull request.

Update Nginx AMI for #171

---

dmaws/rds.py

We do not ever need draft services to be copied over to staging. If they
are for an open or pending framework we definitely don't want them for
legal reasons. If they are for a live framework  they are not very
useful.
Supplier framework records need to be removed for open or pending
frameworks for legal reasons.

Delete all draft services when migrating

---

cloudformation_templates/app_base.j2

Changelog includes:
* [new Amazon Linux AMI](https://aws.amazon.com/blogs/aws/now-available-amazon-linux-ami-2015-09/)
* [Python 2.7.10](https://aws.amazon.com/releasenotes/AWS-Elastic-Beanstalk/2349456301265270)
* Apache and mod_wsgi minor upgrades

Update ElasticBeanstalk platform to v2.0.6

---

vars/common.yml

Update Nginx AMI with gzip

---

dmaws/rds.py

It will be useful for testing things to be able to log in as different users on staging.

Set generic password for all users in migration to staging

---

vars/staging.yml

Yesterday, there was 10 minutes of downtime when I rolled back the staging database.
Checking if I can avoid or mitigate that problem today.

Rollback staging database again again

---

playbooks/roles/nginx/templates/api.j2

restrict API to dev IPs only

---

cloudformation_templates/aws_nginx.json
stacks.yml

build was failing cos of it. don't think i need it anywhere else? stacks.yml already refers to `dev_user_ips`
fao @allait

add dev_user_ips to nginx template

---

vars/staging.yml

Rollback staging database again at the behest of @andrewchong

---

dmaws/rds.py

We have two queries in a row which seem related to each other:
- one query adds supplier frameworks to suppliers who have services (but no supplier frameworks)
- a second query deletes suppliers without supplier frameworks
It looks like the first query exists as setup for the second query.
This pull request makes the second query more specific so that we can remove the first query entirely.
Also, added some more comments that hopefully make it easier to see why we're changing what we're changing.

Delete less suppliers

---

stacks.yml

Move cloudtrail S3 bucket name to credentials

---

dmaws/commands/migratedata.py

I ran into this problem before and I fixed it, but I think in splitting up all my commits into different pull requests I lost these arguments.
✨  works works works ✨

Pass the correct stage

---

dmaws/rds.py

When we migrate data from production to another environment, sensitive
data is removed. This includes data about currently ongoing framework
applications (for frameworks that are `open`), such as draft services
and `supplier_frameworks` info.
Previously we were deleting `supplier_frameworks` data for frameworks
that were `pending` as well as `open`.
We were then removing suppliers who had no entry in the
`supplier_frameworks` table as well as no services (dangling suppliers).
Because `supplier_frameworks` info had been deleted for `pending` and
`open` frameworks but draft services only deleted for `open` frameworks,
this led to a foreign key constraint error on the `draft_services` table
when trying to delete suppliers with no `supplier_framework`.
This commit makes the function only …

Fix bug in `clean_database` script

---

Makefile

Fix a typo in the DB migration make task

---

terraform/Makefile-common

When using the makefile to upload a state file you may want to select
which file to upload.

Add state file variable to make file rule

---

terraform/accounts/main/ci.tf

Allows us to manage Jenkins IP restrictions with Terraform.

Import Jenkins instance security group

---

terraform/environments/preview/main.tf
terraform/modules/application-logs/outputs.tf
terraform/modules/application-logs/variables.tf
terraform/modules/log-streaming/subscriptions.tf
terraform/modules/log-streaming/variables.tf

The new briefs frontend needs application logs setting up, the same way
we do for the other apps.

Add briefs frontend to application logs module

---

scripts/clean-db-dump.sql

We can sanitise the personal details (signer name and role, and the S3
paths to actual signed/countersigned documents) but preserve the fact that
the agreement has been returned.
This means that when logging in as a supplier in Preview or Staging
environments the framework dashboard will be accessible without having
to go through the whole "return your framework agreement" flow.
This will be useful for developers working on the framework dashboard
who do not want to repeatedly return fake framework agreements for
suppliers in order to test their new features.

Sanitise rather than delete framework agreements

---

terraform/modules/iam-users/users/main.tf

User accounts were created manually, so I had to import them into
the Terraform state.

Add Kat and Louise users to the terraform module

---

paas/supplier-frontend.j2

Required before we can merge https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/740

paas supplier-frontend settings: add mailchimp-related settings to template

---

terraform/modules/iam-users/users/main.tf

Remove Paul and Caroline from aws account

Remove Paul and Caroline from aws account

---

terraform/modules/log-streaming/src/main.js

This is really a workaround for nginx, which is unable to log fractional
seconds in anything other than epoch time format, which the awslogs agent
isn't able to interpret as a timestamp, so we're using this lambda function
to perform a little post-processing and re-add the precision back into the
stream.
Already deployed on preview & seems to work ok there.

log-streaming lambda function: substitute epochTime for timestamp in cases it seems appropriate

---

.gitignore
default.nix

Would appreciate if someone could try this out on macos perhaps?

add initial default.nix

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/I21LZspg/161-give-brendan-butler-access-to-all-the-things
https://trello.com/c/spBH8a2f/152-add-dilwoar-to-jenkins-users-he-has-security-clearance-now-also-github-group-for-access-to-credentials-repo-etc

Add Brendan and Dilwoar who both have SC clearance.

---

local.example.nix

Forgot to include this in https://github.com/alphagov/digitalmarketplace-aws/pull/358

add missing local.example.nix

---

README.md
terraform/README.md

https://trello.com/c/qhkTwalM/320-review-digitalmarketplace-aws-terraform-readmemd
Commit messages should give sufficient context (I hope)

Improve terraform README

---

Makefile

Update makefile to use api venv now that we have an updated docker image

Update db migrate definition

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/QtV3sfye/249-remove-david-from-all-the-things
https://trello.com/c/JvyiWIhd/251-remove-murilo-from-all-the-things

Remove David and Murilo from AWS iam users

---

vars/staging.yml

Turn ON maintenance mode for the STAGING environment.

Toggle maintenance mode ON

---

vars/staging.yml

Turn OFF maintenance mode for the STAGING environment.

Toggle maintenance mode OFF

---

scripts/clean-db-dump.sql

We should remove this PII from our dev data

Update clean db dump to overwrite supplier contact details

---

paas/api.j2

We are adding a new route/blueprint to the API for Notify to use to post
the successful/failed delivery of a notification. Given it's a new
token, we need to start injecting it into the API's environment.
https://trello.com/c/vOAUDwnL/446

Inject callback token in environment

---

vars/production.yml

We're still too close to our memory limit, so we'll stay with 10 APIs
for now.
https://trello.com/c/VJ9MdlsQ/310

Back to 10 APIs

---

terraform/modules/iam-users/users/main.tf

Needs an admin to run `make plan` with this creds PR#127

Add new team member with clearance

---

terraform/modules/iam-users/users/main.tf

Removes leavers from IAM roles.

Remove SW, GL, PT, DH, AC, LB

---

terraform/accounts/backups/variables.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/preview/variables.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/production/variables.tf
terraform/environments/staging/s3_buckets.tf
terraform/modules/s3-document-bucket/README.md
terraform/modules/s3-document-bucket/main.tf
terraform/modules/s3-document-bucket/variables.tf

Terraform for preview staging and production s3 buckets.
See [README.md](https://github.com/alphagov/digitalmarketplace-aws/pull/408/files#diff-e3ac418a4fe3b69c3e62825d6d1001d1) for more info

S3 buckets

---

scripts/generate-s3-post-url-data.py
terraform/accounts/backups/s3_buckets.tf
terraform/accounts/main/jenkins_instance_profile.tf

* Bucket owner requires full control to replicate objects
* Jenkins requires `PutObjectAcl` to upload objects with `bucket-owner-full-control`
* Match all for replication is blank string not star 😖

98 set up cross region replication for our backups s3 buckets

---

terraform/modules/router/route53.tf
vars/common.yml
vars/production.yml

This process all needs adding to the manual too.

add antivirus-api subdomain to router's paas and route53's terraform settings

---

scripts/clean-db-dump.sql

We should have been doing this all along really.

Redact phone numbers from users in db cleanup

---

terraform/modules/iam-users/users/main.tf

Trello: https://trello.com/c/fmG2JMgG/464-remove-leaving-developers-from-all-the-things-%F0%9F%91%8B-and-add-jonathan
Create an IAM account for Jonathan, and remove Chris.

Add Jonathan, remove Chris

---

terraform/accounts/development/access.tf
terraform/accounts/production/access.tf
terraform/environments/preview/main.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/preview/s3_replication_buckets.tf
terraform/environments/production/main.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/production/s3_replication_buckets.tf

Trello: https://trello.com/c/TaKJj9U3/141-cross-region-replicate-document-buckets
Now ready for final review:
- created new replication roles/policies for the development and production accounts
- created a new `eu-west-2` provider for Preview and Production
- created new destination S3 buckets for Preview and Production
- added the replication config to the source buckets for Preview and Production

Cross region replication for document buckets

---

terraform/accounts/main/jenkins_instance_profile.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/staging/s3_buckets.tf

Related to https://trello.com/c/eI2PEVIY/202-create-jenkins-job-for-virus-scanning-catchup-script
Pushed to preview & staging, appears to work...

terraform: give jenkins ListBucketVersions permissions on all buckets to be virus scanned

---

.gitignore
scripts/create-hosted-graphite-alerts.py

https://trello.com/c/1QMN0nMG/275-enable-logs-missing-alert-for-av-api
Also reformat

Add "missing logs" HG alert for antivirus api

---

terraform/accounts/backups/cloudwatch.tf
terraform/accounts/development/cloudwatch.tf
terraform/accounts/main/cloudwatch.tf
terraform/accounts/production/cloudwatch.tf
terraform/modules/cloudtrail/README.md

See ticket for more detail...
https://trello.com/c/j0pnOZwL/291-remove-gds-level-cloudtrail

Remove cloutrail logging to GDS buckets, this isdone at a parent account level now

---

paas/brief-responses-frontend.j2

* Change endpoint from _metrics to metrics as per RE Observe request

322-move-metrics-to-metrics-and-expose

---

scripts/clean-db-dump.sql

https://trello.com/c/HFygifh6
Using a smattering of declaration fields from frameworks **past & present**, taking care to only add fields which were actually present on an original declaration, but not based on any actual answers in any way. The pseudorandomness is seeded on the `supplier_id`, `framework_id` combo, so should be stable. Using `md5(...` as pseudorandom function as it's the most readily available tool in postgres.
I'd be interested if anyone can think of any more fields they think should be included.

clean-db-dump.sql: populate more fields of declaration with pseudorandom data

---

terraform/modules/paas/iam.tf

We no longer export metrics using these users

354-delete-paasmetricscollector-user

---

terraform/accounts/development/s3_buckets.tf

Straight conversion to use a policy doc to create policy json

Convert inline policy to iam_policy_document for dev uploads bucket

---

scripts/apply-cleaned-db-to-target.sh

Update apply-cleaned-db-to-target.sh to take s3 argument and upload to s3 not gdrive
https://trello.com/c/0jAgMP0d/405-gdrive-client-alternatives-db-dumps-to-s3-not-drive
https://github.com/alphagov/digitalmarketplace-jenkins/pull/198
Requires:
https://github.com/alphagov/digitalmarketplace-aws/pull/507

405-gdrive-client-alternatives-db-dumps-to-s3-not-drive

---

paas/admin-frontend.j2
paas/api.j2
paas/brief-responses-frontend.j2
paas/briefs-frontend.j2
paas/buyer-frontend.j2
paas/router.j2
paas/supplier-frontend.j2
paas/user-frontend.j2

Reverts alphagov/digitalmarketplace-aws#508
Oops - I didn't push one of the fixes I made locally before merging...

Revert "app environment variables: use ugly "if" statement to switch these to the .apps.internal addresses for preview only"

---

paas/admin-frontend.j2
paas/api.j2
paas/brief-responses-frontend.j2
paas/briefs-frontend.j2
paas/buyer-frontend.j2
paas/router.j2
paas/supplier-frontend.j2
paas/user-frontend.j2

This is a re-attempt at https://github.com/alphagov/digitalmarketplace-aws/pull/508 which actually includes the final fix it needed to work.

[TAKE 2] app environment variables: use ugly "if" statement to switch these to  the .apps.internal addresses for preview only

---

paas/admin-frontend.j2
paas/api.j2
paas/brief-responses-frontend.j2
paas/briefs-frontend.j2
paas/buyer-frontend.j2
paas/router.j2
paas/supplier-frontend.j2
paas/user-frontend.j2

Reverts alphagov/digitalmarketplace-aws#514
This is a reversion of the second reversion of the same PR. However I think it has a chance of working now.

Revert "Revert "[TAKE 2] app environment variables: use ugly "if" statement to switch these to  the .apps.internal addresses for preview only""

---

terraform/environments/preview/main.tf
terraform/environments/production/main.tf
terraform/environments/staging/main.tf
terraform/modules/antivirus-sns/iam.tf
terraform/modules/antivirus-sns/s3-notifications.tf
terraform/modules/antivirus-sns/variables.tf

https://trello.com/c/NNCE0rOd/758-make-terraform-not-require-update-in-multiple-places

758-make-terraform-not-require-update-in-multiple-places

---

terraform/environments/preview/main.tf
terraform/environments/production/main.tf
terraform/environments/staging/main.tf

* Add submissions buckets to av sns notifications
https://trello.com/c/attUxuK5/757-submissions-bucket-not-included-in-antivirus-sns-list

757-submissions-bucket-not-included-in-antivirus-sns-list

---

terraform/accounts/main/codecommit.tf

* Update default branches to master on aws backup repos

151-code-backups-v2

---

vars/README.md
vars/common.yml
vars/preview.yml

* Add a readme file to explain how variables are amalgamated
* Reintroduce _metrics endpoints to preview file
* The ones in common are overriden by the ones in the preview file
https://trello.com/c/wGJZQFxO/427-put-metrics-on-api

427-put-metrics-on-api-2

---

terraform/accounts/backups/main.tf
terraform/accounts/development/main.tf
terraform/accounts/main/main.tf
terraform/accounts/production/main.tf

trello: https://trello.com/c/pSU24fLx/482-security-improvements-csw (first task of the list)
With the upgrade we allow to csw inspector to read our EBS, RDS, and ELB configuration.
https://github.com/alphagov/csw-client-role/compare/v1.0...v1.2

upgrading the csw version

---

terraform/modules/logging/log-metric-filters/main.tf

trello: https://trello.com/c/Lgu5r2Rr/773-exclude-slow-requests-over-a-certain-size-from-triggering-alarms
extra conditions are:
- request begins with POST
- size larger than 500k

extra conditions for slow request alarms

---

terraform/modules/logging/log-metric-filters/main.tf

trello: https://trello.com/c/Lgu5r2Rr/494-exclude-slow-requests-over-a-certain-size-from-triggering-alarms

deMorgan the conditions to get rid of the negation

---

terraform/modules/cloudtrail/cloudtrail/main.tf

trello: https://trello.com/c/39BmiSKF/500-enable-cloud-trail-log-file-validation
documentation: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-validation-intro.html

enabling validation

---

scripts/add-ip-whitelist-route-service.sh

* Do not use reserved var name PATH

457-script-to-add-ip-whitelisted-routes-on-deploy-4

---

paas/admin-frontend.j2
paas/api.j2
paas/brief-responses-frontend.j2
paas/briefs-frontend.j2
paas/buyer-frontend.j2
paas/router.j2
paas/supplier-frontend.j2
paas/user-frontend.j2

* Remove changes to manifest files for internal routes

502-rm-internal-routes-from-preview-for-now-2

---

Makefile

Trello: https://trello.com/c/f1PbVXEW/785-db-backup-app-runs-out-of-memory
Comments only - documenting the quotas for the backup task.
(Planning to put more info into the manual as well)

Comment db-backup Makefile recipe

---

vars/production.yml

Traffic is increasing - let's increase the number of Supplier FE and API instances.

Scale Supplier FE and API instances for G11 traffic

---

terraform/modules/jenkins/jenkins/ec2.tf

* Give jenkins data volume a name

516-enable-ebs-encryption-jenkins-volume-discard-old-volumes-first

---

terraform/accounts/backups/s3_buckets.tf
terraform/accounts/development/s3_buckets.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/preview/s3_replication_buckets.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/production/s3_replication_buckets.tf
terraform/environments/staging/s3_buckets.tf
terraform/modules/cloudtrail/modules/cloudtrail-bucket/main.tf
terraform/modules/jenkins/log_bucket/s3_bucket.tf

trello: https://trello.com/c/w4tnuB26/505-enable-s3-bucket-versioning
also: https://trello.com/c/kyFOBl0M/512-allow-only-encrypted-connection-to-s3-buckets

S3 bucket policies and versioning

---

terraform/accounts/backups/main.tf
terraform/accounts/backups/variables.tf
terraform/accounts/development/main.tf
terraform/accounts/development/variables.tf
terraform/accounts/main/main.tf
terraform/accounts/main/variables.tf
terraform/accounts/production/main.tf
terraform/accounts/production/variables.tf

Add new GDS audit role to accounts with TODO to remove old one when switch is complete
https://trello.com/c/sZ9taJ5n/845-update-to-new-csw-role-for-cyber

845-update-to-new-csw-role-for-cyber

---

terraform/modules/jenkins/jenkins/snapshots.tf

- Fix snapshot time
- Remove condition

Fix issues with jenkins snapshot policy

---

terraform/modules/jenkins/jenkins/ec2.tf

Make it harder to accidentally destroy a Jenkins instance

---

terraform/accounts/backups/main.tf
terraform/accounts/development/main.tf
terraform/accounts/main/main.tf
terraform/accounts/production/main.tf

Switch security audit role commit ref to apply support:* permissions for Support/Trusted Advisor.

Cyber audit support permissions

---

terraform/accounts/main/jenkins_instance_profile.tf
terraform/modules/cloudtrail/modules/cloudtrail-bucket/main.tf

https://trello.com/c/Ijzuk0qY/508-log-file-validation-job

Allow Jenkins to assume 'cloudtrail-validate-logs' roles

---

terraform/modules/iam-users/users/main.tf

Add jonathan
https://trello.com/c/3QfGLar7/932-add-jonathan

932-add-jonathan

---

scripts/check-db-dump-is-decryptable.sh

* Allow pinentry mode
* Get only parent secret key (not child)

gpg2 output and required args changed with 2.x

---

terraform/accounts/main/jenkins.tf

* Add new jenkins
* Remove old jenkins

new-jenkins

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/fsKM8mFg/953-onboard-daniele-to-team

Add Daniele to terraform resources

---

.travis.yml

trello: https://trello.com/c/XDIcNjdk/1012-travis-python-pip-versions

replacing pip with make for installing requirements-dev

---

vars/production.yml

https://trello.com/c/yipUsCmg
api: 7 -> 10 instances
supplier-frontend: 10 -> 14 instances

rescale production instance counts in anticipation of DOS4 closing

---

terraform/accounts/main/jenkins.tf

* Add module for jenkins 3 (fresh jenkins for func test testing)
https://trello.com/c/cM7G38JY/115-create-2nd-jenkins-as-prep-for-changes-to-functional-tests

115-create-2nd-jenkins-as-prep-for-changes-to-functional-tests

---

terraform/accounts/main/jenkins.tf

https://trello.com/c/p69JfraS/1034-do-clean-up-after-pentesting
Decided to fully get rid of jenkins that pentest had access to rather than rotate keys for it.

1034-do-clean-up-after-pentesting

---

terraform/environments/preview/alarms.tf
terraform/environments/production/alarms.tf
terraform/modules/logging/alarms/admin-manager-password-reset/alarms.tf
terraform/modules/logging/alarms/admin-manager-password-reset/variables.tf
terraform/modules/logging/log-metric-filters/main.tf

https://trello.com/c/xeZofjDd/219-alert-when-the-admin-manager-password-is-changed
Look for the log message added in the api:
https://github.com/alphagov/digitalmarketplace-api/pull/967
And trigger and alert when it is seen once.

219-alert-when-the-admin-manager-password-is-changed

---

terraform/accounts/main/jenkins.tf

New jenkins for testing functional tests
https://trello.com/c/JBa2hYjC/294-create-another-jenkins

294-create-another-jenkins

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/AOxxcCSy/1251-remove-jonathan-stefan-from-all-the-things-%F0%9F%91%8B
👋

Remove Jonathan from IAM users

---

terraform/accounts/main/jenkins.tf

* Remove extranoues J3 CI
https://trello.com/c/3jpspJCx/1282-extra-ci

1282-extra-ci

---

default.nix
terraform/modules/iam-users/users/main.tf

https://trello.com/c/VXQ9pvgd
Also sneak in a boring nix fix.

terraform: add paulavalenca user

---

vars/production.yml

https://trello.com/c/q2gsii8q/1523-first-platform-scaling
Scaling app memory to handle G-Cloud 12 traffic increase. We're not scaling the number of instances just yet.

Scale app memory for G12

---

terraform/modules/iam-users/users/main.tf

trello: https://trello.com/c/5sDMdneI/1562-remove-ben-from-all-the-things-%F0%9F%91%8B

removing ben and al

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/xwIwIc8x/1591-add-brett-to-things
Creates the IAM resource for Brett's AWS account (see https://github.com/alphagov/digitalmarketplace-credentials/pull/316).

Create Brett's AWS account

---

vars/preview.yml

Set maintenance mode to 'recovery' for the PREVIEW environment.

Set maintenance mode to recovery

---

vars/preview.yml

Set maintenance mode to 'live' for the PREVIEW environment.

Set maintenance mode to live

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/IpZd8QFo/1639-add-gideon-to-all-the-things-remove-rob
Create a new user for Gideon on the `digitalmarketplace` AWS account.

Add Gideon IAM user, remove Rob

---

.travis.yml
terraform/modules/log-streaming/lambda.tf

See Trello: https://trello.com/c/X4v1uBUh
Just maintenance stuff, ensuring we are using the latest and it's consistent across. 
I ran `terraform plan` against Preview and all is :+1:

Upgrade terraform

---

vars/production.yml

bump instances

---

vars/production.yml

50% supplier instances increase to cope with the sustained traffic

scaling suppliers to 30

---

vars/production.yml

scaling up in anticipation of increased traffic

increase supplier frontend instances and memory

---

terraform/modules/iam-users/users/main.tf

add benjamin gill

---

terraform/README.md

I've got terraform 0.13 installed, and was confused as to why it wasn't working.

Make it clear we're using terraform 0.11.x

---

vars/production.yml

scale up in advance of DOS5 opening.
(We should keep an eye on traffic to see if it does actually increase in this period)

scale up supplier frontend and api

---

vars/production.yml

Revert scale up for DOS 5 and previous scale up for G12 which was kept on, now we are past peak.

Revert 741 scale up dos 5

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/sKotmkP7/1894-remove-kat-from-all-the-things-%F0%9F%91%8B

remove kat aws user

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/XTBQpMBa/1986-add-alex-to-some-of-the-things
add @alex9smith IAM user.

add alex smith IAM user

---

paas/supplier-frontend.j2

https://trello.com/c/NcLdEdYq/2082-incident-db-api-contract-has-expired

temporarily remove vars

---

vars/staging.yml

part of https://trello.com/c/nvb460Rx/569-2-decide-and-test-deployment-method-on-staging
N.B. We need to include existing services so they don't get overridden.

bind staging frontend apps to redis

---

vars/staging.yml

temporarily disable rate limiting

---

vars/staging.yml

part of https://trello.com/c/nvb460Rx/569-2-decide-and-test-deployment-method-on-staging

Enable redis session type on staging

---

terraform/accounts/main/jenkins.tf

https://trello.com/c/nCAuU2nf/558-give-the-pentester-a-way-to-test-our-jenkins-instance

Create a new Jenkins instance for the ITHC

---

Makefile

https://trello.com/c/XjcK0K3g/737-upgrade-environments-to-postgres-12
Upgrade postgres container to match what we are running on PaaS﻿

bump postgres container version

---

vars/preview.yml

Set maintenance mode to 'maintenance' for the PREVIEW environment.

Set maintenance mode to maintenance

---

terraform/environments/production/alarms.tf

Trello: https://trello.com/c/usuc7ANJ/509-5-upgrade-aws-repo-to-use-terraform-v012
Accidentally removed in 55a7dcefcce99c6d2c697a19a482778676e0ee90

Re-instate prod alarm

---

vars/preview.yml

https://trello.com/c/pHlDhj5c/565-1-test-the-paas-data-backup-restore-process
(Note we need to include the other services so they don't get overridden)

bind to restored db

---

vars/preview.yml

https://trello.com/c/pHlDhj5c/565-1-test-the-paas-data-backup-restore-process
Now restore has completed we can revert to previous DB name

Revert "bind to restored db"

---

paas/api.j2
paas/supplier-frontend.j2

https://trello.com/c/MJExPLo2/846-3-remove-g12-recovery-code-and-pii
Reverts #828 and #797

Remove G12 recovery IDs from app manifests

---

terraform/accounts/main/codecommit.tf

update default branch of deployable apps for codecommit

---

terraform/accounts/main/codecommit.tf

update frontend toolkit main branch in codecommit

---

terraform/accounts/main/codecommit.tf
terraform/modules/logging/alarms/README.md
vars/README.md

https://trello.com/c/DrVWMkcZ/2169-rename-default-branches-on-our-repos-from-master-to-main﻿

replace master references with main

---

terraform/accounts/main/codecommit.tf

https://trello.com/c/DrVWMkcZ/2169-rename-default-branches-on-our-repos-from-master-to-main﻿

update functional tests branch

---

terraform/accounts/main/codecommit.tf

update utils branch to main

---

terraform/accounts/main/codecommit.tf

update scripts branch

---

terraform/accounts/main/codecommit.tf

change apiclient default branch

---

terraform/accounts/main/codecommit.tf

update apiclient default branch

---

terraform/accounts/main/codecommit.tf

rename default branch of docker-base

---

terraform/modules/iam-users/users/main.tf

He's moving to the Design System team
https://trello.com/c/ZEVdXNMd/2213-remove-laurence-from-all-the-things-%F0%9F%91%8B

Remove Laurence's AWS account

---

vars/staging.yml

https://trello.com/c/c00Ix4wd/2230-p4-database-dump-failing-on-staging
use restored DB to resolve incident

use restored DB

---

terraform/accounts/main/codecommit.tf

reflect branch rename

---

terraform/environments/preview/main.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/staging/main.tf

https://trello.com/c/HCf26VVT/922-3-645-bucket-without-default-encryption-enabled
Add encryption on some preview buckets to test this works as expected before rolling out further.

add encryption to preview buckets

---

terraform/accounts/main/codecommit.tf

Rename default branch of digitalmarketplace-agreements

---

terraform/accounts/main/codecommit.tf

Change default branch of digitalmarketplace-performance-testing

---

terraform/accounts/main/codecommit.tf

Rename default branch of digitalmarketplace-bad-words

---

terraform/accounts/main/jenkins.tf

https://trello.com/c/cacoWXHC/63-5-upgrade-the-version-of-python-on-jenkins-to-at-least-38
Make new instance primary, rename old instance to allow for switching back in case of issues

Make new instance primary

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/wkv1DxMT/2289-off-board-gideon-%F0%9F%91%8B 👋

remove gideongoldberg iam user

---

terraform/modules/logging/alarms/README.md

Document manual control of SNS subscriptions

---

.gitignore
terraform/modules/iam-users/users/main.tf

- Add .idea to git ignore file
- Add Jack, John, Will and Crispin to AWS

Add ccs techops engineers

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/MYdNqOcQ/2331-remove-brett-%F0%9F%91%8B
https://trello.com/c/lvNKNOnS/2329-remove-alex-%F0%9F%91%8B
They've both just left the team: https://crown-commercial-service.github.io/digitalmarketplace-manual/managing-people-and-secret-things/accounts.html#aws
Will be deployed alongside https://github.com/Crown-Commercial-Service/digitalmarketplace-credentials/pull/430

Remove Alex and Brett

---

terraform/accounts/main/codecommit.tf

See https://trello.com/c/DrVWMkcZ/2169-rename-default-branches-on-our-repos-from-master-to-main for more details

Rename branch from master to main for digitalmarketplace-visual-regression

---

Makefile
scripts/check-terraform-formatting.sh
terraform/accounts/development/s3_buckets.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/preview/s3_replication_buckets.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/production/s3_replication_buckets.tf
terraform/environments/staging/s3_buckets.tf
terraform/modules/cloudtrail/modules/cloudtrail-bucket/main.tf
terraform/modules/jenkins/log_bucket/s3_bucket.tf
terraform/modules/s3-document-bucket/main.tf

Discovered whilst looking into https://github.com/Crown-Commercial-Service/digitalmarketplace-aws/pull/1033
Our formatting wasn't up to date. So I fixed this, and also the problem with the Github Action that meant we missed it. See commits for details.

Fix formatting - and formatting tests

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/XCOKRWB4/2378-add-tom-to-all-the-things
Welcome @tberey!
Following the normal process: https://crown-commercial-service.github.io/digitalmarketplace-manual/managing-people-and-secret-things/accounts.html#aws

Add Tom Berey to AWS

---

terraform/modules/iam-users/users/main.tf

He was removed manually - update Terraform to reflect this.

Remove Crispin

---

terraform/modules/iam-users/users/main.tf

Remove BGill accounts
