Crown-Commercial-Service/digitalmarketplace-aws

cloudformation_templates/aws_digitalmarketplace_api_env.json
cloudformation_templates/aws_digitalmarketplace_api_rds_dev_access.json
cloudformation_templates/aws_elasticsearch.json
cloudformation_templates/aws_elasticsearch_dev_access.json
playbooks/roles/aws_digitalmarketplace_api/tasks/main.yml
playbooks/roles/aws_elasticsearch/tasks/main.yml
playbooks/setup.yml
playbooks/teardown.yml
scripts/run.py

Creates AWS security group rules to enable remote access to Elasticsearch and RDS database from given IPs
I haven't moved SSH access out of the Elasticsearch CloudFormation template since it's required for provisioning (and so needs to be in the same state as elasticsearch tasks). 
SSH access for all Elastic Beanstalk instances is always enabled by Amazon.

Add tasks to create/remove dev access rules

---

cloudformation_templates/aws_digitalmarketplace_api_env.json

List of permissions from http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.iam.roles.aeb.html
> The following example shows one statement that gives a broad set of permissions to AWS products that AWS Elastic Beanstalk uses to manage applications and environments and includes permissions to create an instance profile and view a list of available instance profiles

Add IAM Instance Profile to digitalmarketplace-api Elastic Beanstalk instances

---

cloudformation_templates/aws_digitalmarketplace_api_app.json
cloudformation_templates/aws_digitalmarketplace_api_env.json
cloudformation_templates/aws_elasticsearch.json
cloudformation_templates/aws_elasticsearch_dev_access.json
playbooks/roles/aws_elasticsearch/tasks/main.yml

Resource names are internal to CloudFormation stack so they don't need to be globally unique.
Not having app prefixes makes it easier to reuse parts of templates (which we'll have to do with api/search/admin templates)

Remove app name prefixes from CloudFormation resource names

---

cloudformation_templates/aws_dev_access.json
cloudformation_templates/aws_digitalmarketplace_api.json
cloudformation_templates/aws_elasticsearch.json
playbooks/roles/aws_digitalmarketplace_api/tasks/main.yml
playbooks/roles/aws_elasticsearch/tasks/main.yml
playbooks/setup.yml
user.yml.sample

Creates an ELB in front of Elasticsearch and adds ELB URL to elasticsearch and digitalmarketplace-api stack outputs so that we can use them to configure apps that require access to elasticsearch/API.

Add Elasticsearch ELB and ELB URLs to stack outputs

---

playbooks/provision.yml
playbooks/setup.yml
scripts/run.py

Changes flags/options in `scripts/run.py` so now it looks like:
```
./scripts/run.py development test-branch setup -t elasticsearch -e key=val -d
```
Will add script docs to `README.md` once we're happy with the interface.

Improve run script

---

cloudformation_templates/aws_digitalmarketplace_api.json
cloudformation_templates/aws_rds_database.json
stacks.yml
user.yml.sample
vars/common.yml

Having the DB instance outside the api stacks makes it easier to change Elastic Beanstalk app/env stacks and would allow us to reuse the database for multiple environments later.

Move RDS database to a separate CloudFormation stack

---

dmaws/build.py
dmaws/deploy.py

Add a file containing the version label to the release artefact. The
intention is that this will be picked up by apps and shown through their
status URL.

Add version file to artefact

---

.gitignore
dmaws/build.py
dmaws/commands/release.py
dmaws/stacks.py
scripts/jenkins-release.sh
stacks.yml

The release command is going to be called from Jenkins. This means that
there will not be an existing, safe chekout of the app repositories.
This commit solves that problem by changing release to accept an app
name and then cloning the app's repo locally.

Clone app when releasing

---

dmaws/cli.py
dmaws/stacks.py
dmaws/utils.py
scripts/jenkins-release.sh

It is not needed for releases from the jenkins machine.
This change prevents the user.yml being added to the vars files if it
does not exist.
It also changes the built stack parameters to be lazy so that some can
be evaluated without all being evaluated. This is needed for the release
command so that parameters not required for release do not have to be
evaluated.

Do not require user.yml to be present

---

cloudformation_templates/aws_digitalmarketplace_admin_frontend.json
cloudformation_templates/aws_digitalmarketplace_api.json
cloudformation_templates/aws_digitalmarketplace_search_api.json
dmaws/stacks.py
dmaws/utils.py
stacks.yml

Takes all `EnvVar*` parameters from the stack parameters list and:
1. Adds a parameter declaration to CloudFormation template
2. Adds OptionSetting to set parameter value to environment variable with the `param_to_env(name)` in the Elastic Beanstalk environment
Loaded CloudFormation template is run through jinja2 using selected values from the stack as context.
Right now the only variables available to jinja are:
* `environment_variables` – a subset of parameter names and
* `param_to_env` – a transform function to get environment variable
name out of parameter name.
Parameter is added to 'environment_variables' if its name starts with 'EnvVar' (CloudFormation doesn't allow underscores in parameter names so direct mapping using actual environment variable names doesn't work. And 'Env' …

Run CloudFormation templates through Jinja

---

dmaws/build.py
dmaws/commands/release.py
dmaws/deploy.py
dmaws/utils.py

Wait for the status of the Beanstalk application to go back to 'Ready'  before exiting. This status unfortunately doesn't tell us whether the release was successful, so also track the event stream, print them and cause dmaws to fail if any errors are encountered.
There are also a couple of little bug fixes to the release process in here as well because here is where I found them. I can move them into a separate pull request if people think it's necessary.

Wait for ready status on release

---

dmaws/cli.py
dmaws/commands/release.py
dmaws/utils.py

Fix the `admin-frontend` `KeyError` and abort the build if the subprocess fails

Fixes for the admin-frontend release command

---

dmaws/deploy.py

When deploying to preview we have hit the API throttling limit when
waiting for the deploy to happen.

Increase sleep between wait loops

---

cloudformation_templates/aws_digitalmarketplace_admin_frontend.json
cloudformation_templates/aws_digitalmarketplace_api.json
cloudformation_templates/aws_digitalmarketplace_search_api.json

Upgrade Digital Marketplace instances running in Elastic Beanstalk to Amazon Linux 2014.09 v1.2.0.

Upgrade instances to Amazon Linux 2014.09 v1.2.0

---

dmaws/build.py
dmaws/commands/release.py

- The tag must be force pushed because it already exists and we will be
recreating it each time we deploy.
- When deploying to staging or production the repository will not, by
default be on the tag we're releasing so we must tag the specific
commit.

Fix deployed-to-{stage} tagging

---

cloudformation_templates/aws_digitalmarketplace_admin_frontend.json
cloudformation_templates/aws_digitalmarketplace_api.json
cloudformation_templates/aws_digitalmarketplace_search_api.json
cloudformation_templates/aws_route53_hosted_zone.json
stacks.yml
vars/development.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

Create a Route53 zone and then create domains for each app of the form
`{ stage }-{ environment }-{ app name }.{ root domain }`
This is a precursor to setting up SSL and CloudFront.

Add Route53 managed domains for all apps

---

cloudformation_templates/app_base.j2
cloudformation_templates/aws_elasticsearch.json
dmaws/commands/deploy.py
dmaws/commands/loaddata.py
dmaws/deploy.py
dmaws/stacks.py
dmaws/utils.py
requirements.txt

Downloads a database dump from S3 and runs it on the environment RDS instance.
Runs Elasticsearch import script from the digitalmarketplace-api repository with environment API and Elasticsearch as arguments.
A lot of this will change once we have write endpoints on api and search-api that would allow loading data throught them instead of using the databases directly.

Add loaddata command and some related changes

---

cloudformation_templates/aws_cloudfront_app.json
cloudformation_templates/aws_cloudfront_www.json
cloudformation_templates/aws_s3.json
stacks.yml

- This is HTTP only until we can get the necessary SSL certificates.
- PriceClass_100 only includes edge locations in the US and Europe. Given
most of our customers are UK this cheapest option seems sensible.
- All methods are allowed because CloudFormation only allows two
options, [GET, OPTIONS] or everything and we need POSTing.
- As we only have one frontend app at the moment it is set as the
DefaultCacheBehaviour. Admin should not ultimately be the default.

Add cloudfront for API and Admin frontend.

---

cloudformation_templates/app_base.j2

This ensures that deploys only go out to one instance at a time.
See:
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.rolling-version-deploy.html
I have tested this by increasing the number of instances and running a
deploy while providing constant load with vegeta. When the app is
experiencing no load the deploys appear to overlap. However, when there
is load and these configuration options are set there are no 504s. When
these options are not set there are a small number of 504s (3%).

Add Beanstalk configoptions for rolling deploy

---

dmaws/commands/release.py
setup.py

If preview release failed to deploy for some reason, rerunning the task would fail when creating the release tag.
Instead, if the current release version already exists the release command will use it for the EB deploy process.

Release existing version to preview

---

vars/common.yml

We should have an odd number higher than one for our instance count.

Increase elasticsearch instance count to 3

---

dmaws/commands/loaddata.py

The api import scripts transforms service documents into G5 format, the search-api script imports documents in the format supported by the search-api.

Fix loaddata command to use ES script from search-api

---

cloudformation_templates/aws_cloudfront_www.json
stacks.yml

This changes the byers app to be the default origin. It also serves the supplier app under `/supplier` and the admin app under `/admin`. During the architecture meeting we seemed to all agree that the admin app should live on a subdomain rather than through CloudFront. What was the consensus on that (cc/ @minglis).
This has some implications for the supplier and admin apps. All their routes must be under `/supplier` and `/admin` respectively or they will not work through the www sub-domain. This will require some changes.

Add the supplier and admin frontends to cloudfront

---

dmaws/commands/debug.py
stacks.yml

`preview-preview-<app>.domain` becomes `preview-<app>.domain`, while `preview-master-<app>.domain` will still keep the environment.
Won't clash with cloudfront in preview/staging thanks to the `-cloudfront` CNAME suffix.
Won't clash with production cloudfront since the apps will still have the `production-` prefix.

Stage-only CNAME for main stage environments

---

cloudformation_templates/aws_cloudfront_www.json

A path pattern of `/admin` will just match the path `/admin`. If we need to match all paths starting with `/admin` it needs to be `/admin*`.

Glob path patterns for WWW distribution

---

cloudformation_templates/app_base.j2
cloudformation_templates/aws_monitoring.json
stacks.yml

This change gives the beanstalk EC2 instances access to write log events to CloudWatch and also creates the CloudWatch log group to be used by all apps in the environment.

Add CloudWatch logs

---

cloudformation_templates/app_base.j2
cloudformation_templates/aws_digitalmarketplace_admin_frontend.json
cloudformation_templates/aws_digitalmarketplace_supplier_frontend.json

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html
docs mention that the /static/ option name can be any arbitrary value.
Uses template block since there's no parameter that has the correct
value and the admin/supplier paths are hardcoded in the CloudFront template.

Set static URL prefixes for admin and supplier apps

---

cloudformation_templates/app_base.j2
stacks.yml
vars/development.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

This adds the SSL certificate to the EB environment, switches on HTTPS
and switches off HTTP. This means that EB apps will no longer respond
over HTTP.

Switch all EB apps to HTTPS

---

cloudformation_templates/app_base.j2

The awslogs daemon is failing because it does not have this permission.
This permission was originally removed because we're creating the log group
in our CloudFormation code.

Add logs:CreateLogGroup permission to EB instances

---

cloudformation_templates/aws_cloudfront_app.json
cloudformation_templates/aws_cloudfront_www.json
stacks.yml
vars/development.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

This introduces IamCertificateId which is a different identifier to the
same IAM SSL certificates. This is needed because CloudFront requires a
different ID to the one that Elastic Beanstalk uses.
TLSv1 is required as minimum protocol version because we're using
sni-only.

Serve CloudFront over SSL

---

dmaws/cloudformation.py

Otherwise wait_for blocks forever if the CF stack fails to ROLLBACK
due to missing permissions.

Add ROLLBACK_FAILED to the list of wait_for statuses

---

cloudformation_templates/app_base.j2

This is used by the CloudFormation rules in .ebextensions in the apps to
generate the log stream names.

Add ApplicationName custom option

---

stacks.yml

dmutils standardises the environment variables holding the API URLs and
auth tokens. This change leaves the old environment variables in place
to avoid breaking changes during the switch over.

Update API env vars for dmutils

---

cloudformation_templates/aws_elasticsearch.json
cloudformation_templates/aws_nginx.json
dmaws/commands/create.py
packer_templates/elasticsearch.json
packer_templates/nginx.json
playbooks/elasticsearch_playbook.yml
playbooks/nginx_playbook.yml
playbooks/roles/cloudwatch/defaults/main.yml
playbooks/roles/cloudwatch/tasks/main.yml
playbooks/roles/cloudwatch/templates/elasticsearch_awslogs.conf.j2
playbooks/roles/cloudwatch/templates/nginx_awslogs.conf.j2
stacks.yml
vars/common.yml

Adds cloudwatch streams for nginx and elasticsearch.
Provided awslogs configs will send nginx access_log and general elasticsearch cluster log to cloudwatch.
New AMIs contiain the cloudwatch ansible role and have awslogs preinstalled.

nginx and elasticsearch AMI cloudwatch logs

---

.travis.yml
cloudformation_templates/aws_elasticsearch.json
cloudformation_templates/aws_nginx.json
dmaws/build.py
dmaws/cloudformation.py
dmaws/commands/create.py
dmaws/commands/delete.py
dmaws/context.py
dmaws/deploy.py
dmaws/stacks.py
dmaws/utils.py
requirements.txt
setup.py
stacks.yml
tests/helpers.py
tests/test_deploy.py
tests/test_stack.py
tests/test_utils.py

This is a lot of small stuff bundled together, I can split them into separate pull requests if needed.
* Returns stack create/delete/update errors as exit code 1 (I'll silence the return code in Jenkins for now, since it will always fail due to EB apps being in DELETE_FAILED state)
* Cleans up and structures log output
* Renames the elasticsearch ELB to meet the length requirements for production (requires recreating the ASG, so the cluster will be wiped)
* Fixes an error with Cloudformation RateLimit exceptions being treated as "stack missing" responses
* Restores python3 compatibility since ansible is no longer a requirement

Create and delete exit status

---

stacks.yml
user.yml.sample
vars/common.yml

To send emails the app needs a Mandrill key, secret password salt and a 'namespacing' salt.
This adds these three parameters as environment variables for the supplier app.
This PR should be merged before: https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/17

Add new environment vars for sending password reset emails

---

cloudformation_templates/aws_rds_database.json
stacks.yml
vars/development.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

In development and preview RDS instances do not need to be MultiAZ in
staging and production they do.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-multiaz

Add MultiAZ parameter to RDS instances

---

cloudformation_templates/aws_nginx.json
playbooks/roles/nginx/tasks/main.yml
playbooks/roles/nginx/templates/api.j2
playbooks/roles/nginx/templates/assets.j2
playbooks/roles/nginx/templates/nginx.conf.j2
playbooks/roles/nginx/templates/www.j2
vars/common.yml

When proxy_pass is used with a predefined URL nginx will resolve
the host during startup and will cache the IP address indefinitely.
This is a problem when proxying requests to AWS ELBs, since ELB IPs
change without notice.
To force nginx to re-resolve DNS proxy_pass destination must be set
to a variable and resolver must be defined in server configuration.
Nginx can't use the nameserver IP from system resolv.conf, so we're
passing it in as another variable.
Since we set resolver in nginx.conf and the variable is only set
in cloud-init stage nginx.conf is now run during instance-config.
nameserver_ip is set by user data cloud-init script by running the `resolv.conf` through `awk`.

Configure nginx to re-resolve upstream hosts

---

cloudformation_templates/aws_nginx.json

Missing space prevented ansible from starting up with "unknown playbook"
error.

Fix aws_nginx cloud-init script typo

---

cloudformation_templates/aws_monitoring.json
cloudformation_templates/aws_rds_database.json
stacks.yml
vars/common.yml
vars/development.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

Number of days to keep automatic snapshots around. Set to 1 for
non-production and 30 for production.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-BackupRetentionPeriod
A snapshot identifier to use to restore a database from a snapshot. It is defaulted to blank. The idea being it would be provided as a custom variable to restore an environment to a snapshot.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbsnapshotidentifier
A few things get added in this commit:
- A DeletionPolicy is added to the DBInstance resource to Snapshot when
the resource is deleted
- If DBSnapshotIdentifier is provided DBName is not provided. If a
DBName is …

Add rds backup and snapshot

---

playbooks/roles/nginx/templates/www.j2

This allows /suppliers-guide to be a route on the buyers app.
The regular expression will only match strings are exactly /suppliers or
start with /suppliers/

Make suppliers nginx location a regex

---

packer_templates/elasticsearch.json
packer_templates/nginx.json
vars/common.yml

This allows both the production and development accounts access to the
nginx and elasticsearch AMIs.
See: https://www.packer.io/docs/builders/amazon-ebs.html#ami_users
Make suppliers nginx location a regex
See: https://github.com/alphagov/digitalmarketplace-aws/pull/86

Update nginx ami

---

vars/common.yml

Includes https://github.com/alphagov/digitalmarketplace-aws/pull/86
Sorry, the previous PR didn't actually include the change.

Upgrade nginx AMI

---

vars/production.yml

See: https://www.pivotaltracker.com/story/show/92327910
Increase the number of EC2 instances per app in production to 3. This
matches the number of availability zones for the EU west region. The
assumption is that elastic beanstalk will automatically create the
instances across the availability zones. This will be tested when this
goes out.

Increase the number of app instances on production

---

vars/preview.yml
vars/production.yml
vars/staging.yml

It is hard to tell where a monitoring alert came from. This is a simple
way of making it clear which account / stage the alert came from.

Add account and stage for monitoring emails

---

vars/production.yml

The default parameters beanstalk rolling update require the
max_instance_count to be at least one larger than the min_instance_count
so that one instance can be changed without going either over or under
the limits.
See:
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html

Increase max instace count on production

---

cloudformation_templates/aws_monitoring.json

SNS topics cannot be updated updated with CloudFormation. The hope is that CloudFormation will remove the old topic and create a new one.
I have tested this on preview and reports that it creates the new SNS topic and RDS event subscription, and deletes the old RDS event subscription but makes no mention of the old SNS topic. However, checking through the AWS console shows that the old SNS topic is no longer there.

Rename monitoring SNS topic

---

vars/production.yml

This reverts https://github.com/alphagov/digitalmarketplace-aws/pull/93 which in turn reverted https://github.com/alphagov/digitalmarketplace-aws/pull/89 EC2 instance limits have been increased so this can go out now.

Increase instance counts on production

---

vars/production.yml

The CloudFormation stacks have become confused because we hit our EC2
instance limit. This change basically just changes the input parameters
to the affected stacks to force them to re-run. #lolaws

Bump instance max count on eb

---

playbooks/roles/nginx/tasks/main.yml
vars/common.yml

Uses nginx apt repository to install the latest version
Allows installing nginx 1.8.0 on Ubuntu 14.04

Update nginx to 1.8

---

dmaws/build.py
dmaws/utils.py
tests/test_build.py
tests/test_utils.py

Expects project build script to output artefact paths to be included
into the release archive. One path per line.
This requires the build script to redirect any other output to STDERR.
No longer includes any paths on top of the git archive by default.
Adding directory to archive verifies that path is relative to the
project root to prevent root path traversal (eg doesn't allow adding
'/' or '../')

Update frontend artifacts paths included in the release

---

playbooks/roles/nginx/tasks/main.yml
playbooks/roles/nginx/templates/nginx.conf.j2
vars/common.yml

nginx 1.8 package provided by the nginx apt repository doesn't seem
to create them by default. Instead we create them using ansible.
Also removes loading configuration files from conf.d/, since that's
where the 1.8 keeps default configuration examples.

Fix nginx sites directories

---

dmaws/build.py

Since we're using the output to add paths to the release archive it
needs to be captured, otherwise run_cmd returns None.

Fix project build script not capturing output

---

dmaws/build.py
dmaws/utils.py
tests/test_build.py

Setting stderr to subprocess.STDOUT means it's capture whenever
STDOUT is being captured. Setting it to None by default makes run_cmd
only capture STDOUT. Can be overwritten by passing `subprocess.STDOUT`
as argument value for `stdout`.
We use output capture to parse results of git commands, but they're
written to STDOUT so this change shouldn't affect the release process.
Empty lines (or a trailing \n) leads to the root project directory
being added to the release archive.

Fix build stderr capture

---

cloudformation_templates/aws_elasticsearch.json

Limited to only port that ES uses: port 9300,
instead of all ports.
Pivotal story: https://www.pivotaltracker.com/story/show/97093870
Paired with @allait

Change Elastic search cluster firewall

---

cloudformation_templates/aws_elasticsearch.json

Applying previous change removed the Ingress rule instead of updating it.
Cloud formation logs show that a new resource was created before cleanup
deleted the old one, but the result in security group didn't have the new rule.
Changing the resource name to trigger another update.

Rename Security Group Ingress resource to trigger an update

---

cloudformation_templates/aws_elasticsearch.json

Not setting the protocol sets ports to 'all', despite the port range
being limited.

Specify protocol for elastic search ClusterDiscoveryIngressGroup

---

stacks.yml

Documents for draft services will go into a separate bucket that is not
visible to the outside world. After submissions close we will virus
scan them before migrating only the successfull ones into the live
docuemnts S3 bucket.

Add S3 bucket for G7 draft documents

---

cloudformation_templates/aws_nginx.json

Updates the ELB TLS policy to ELBSecurityPolicy-2015-05, which disables
DHE ciphersuites in response to the [Logjam attack](https://weakdh.org)
https://forums.aws.amazon.com/ann.jspa?annID=3061
This changes the SSLLabs SSL Report overall rating from "B" to "A".

Set nginx ELB TLS cipher policy

---

cloudformation_templates/aws_digitalmarketplace_supplier_frontend.json

The app prefix was changed to /suppliers/, but the Elasticbeanstalk
assets prefix was not updated, which means that static assets were
served by the python app and not directly by Apache.

Fix supplier-frontend static assets URL prefix

---

vars/production.yml

This can be done before we go live. The plan is to manually create a
hosted zone for beta.digitalmarketplace.service.gov.uk after this been
deployed and manually import the zone file (using cli53 command line
tool).
[cli53](https://github.com/barnybug/cli53)

Update production root domain and SSL certificate

---

vars/staging.yml

This tests out the documentation at
https://github.gds/pages/gds/digitalmarketplace-manual/rds-backup-recovery.html
in the run up to going live.

Roll back to a new RDS snapshot ID

---

cloudformation_templates/app_base.j2
cloudformation_templates/aws_digitalmarketplace_admin_frontend.json
cloudformation_templates/aws_digitalmarketplace_supplier_frontend.json
cloudformation_templates/aws_nginx.json
packer_templates/nginx.json
playbooks/roles/nginx/templates/api.j2
playbooks/roles/nginx/templates/assets.j2
playbooks/roles/nginx/templates/healthcheck.j2
playbooks/roles/nginx/templates/nginx.conf.j2
playbooks/roles/nginx/templates/www.j2
stacks.yml
user.yml.sample
vars/common.yml

[#99144578](https://www.pivotaltracker.com/story/show/99144578)
Not setting `/_status` as health check URL means that ELB might mark
the instance as healthy before the app is actually up (Apache responds
on '/' with default EB welcome page).
`?ignore-dependencies` is a simplified status page that always returns
`{"status": "ok"}` and doesn't forward the request to the APIs or DB.
Request to 'http://localhosts' was handled by the default healthcheck
server, which always returns an empty 200 response.
Instead, we explicitly send the request to the buyer frontend.
/_status makes sure request is picked up by the healthcheck server
[#96672646](https://www.pivotaltracker.com/story/show/96672646)
Sets nginx allow rules using the list if IP addresses from the
`admin_user_ips` list. Requests from …

Nginx and ELB status fixes

---

playbooks/roles/nginx/templates/www.j2
vars/common.yml

Tested everything else:
* User IP forwarding works, real IPs in logs now
* Admin access work
* `service nginx status` and `logrotate` fixed

Nginx config typo fix

---

cloudformation_templates/app_base.j2
cloudformation_templates/aws_monitoring.json
stacks.yml

This will also alarm on Beanstalk state changes. It may be too noisy, if so we can pass the SNS topic in a custom option.
The monitoring stack will not be rebuilt because only the outputs have changed. This introduces a dummy resource to force a rebuild. This resource will be removed after this has been applied.

Notify on beanstalk alarms

---

cloudformation_templates/aws_route53_root_records.json
stacks.yml

Add the MX and SPF records from Dyn for email on digitalmarketplace.service.gov.uk and a TXT record that we think is for verifying ownership of the site.
Also adds the development subdomain.

Add root DNS records

---

cloudformation_templates/aws_route53_root_records.json

The ResourceRecords field must be a list of strings.

Fix Route53 root records

---

cloudformation_templates/aws_route53_root_records.json

Because Route53 fails if they're not.

Surround SPF and TXT records with double quotes

---

cloudformation_templates/aws_monitoring.json

Performing more complex metric filters is much easier with JSON logs.
See: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/FilterAndPatternSyntax.html#d0e11216

Add a CloudWatch log group for JSON logs

---

dmaws/commands/deploy.py

If this blank line is in the docstring then click blows up. This is a bug in click but it's easy to fix here.

Fix deploy command docstring

---

cloudformation_templates/app_base.j2
cloudformation_templates/aws_monitoring.json
stacks.yml

It is easier and less error prone to pass this in to the application stacks rather than generating it in each application stack.

Add JSONLogGroupName to the application stacks

---

cloudformation_templates/aws_nginx.json
playbooks/roles/nginx/defaults/main.yml
playbooks/roles/nginx/files/robots.txt
playbooks/roles/nginx/tasks/main.yml
playbooks/roles/nginx/templates/nginx.conf.j2
playbooks/roles/nginx/templates/www.j2
vars/common.yml

Default `client_max_body_size` is 1Mb and nginx returns 413 if
requests exceeds the size limit.
[#99500206](https://www.pivotaltracker.com/story/show/99500206)
Adds robots.txt file served from the root of www. Disallows any
URLs starting with `/admin` or `/suppliers`, so that both root
pages and all other pages of admin and supplier apps are not
indexed.
Since suppliers-guide was moved to `/g-cloud/suppliers-guide`,
there's no need to add an allow rule for it.
By default Auto Scaling Groups use EC2 instance status
checks to add or remove instances from the group. Which
means that even if the instance doesn't respond to the
ELB health checks it will still be "InService".
Changing the ASG health check to "ELB" makes sure that only
instances that pass all attached ELB health checks are added …

nginx robots.txt, max request size and ASG update policy

---

cloudformation_templates/aws_nginx.json
playbooks/roles/nginx/templates/assets.j2
vars/common.yml

Connection draining will keep instance InService for the given
time to allow existing requests to finish. This way nginx AMI
updates could be applied without interrupting or failing any
requests.
This is the same setting we've enabled to fix failing requests on
application deploys.
404 page forwarded from the buyer frontend to handle missing service
documents references static files required to display the page.
When handling requests for /static URLs nginx tries to request them
from S3, gets a 404 and returns the same buyer frontend 404 page.
Adding a /static location forwarded to the buyer frontend fixes the
issue.

nginx connection draining

---

cloudformation_templates/aws_dev_access.json
cloudformation_templates/aws_nginx.json
dmaws/stacks.py
stacks.yml
tests/test_stacks_file.py
user.yml.sample
vars/common.yml

[#99310600](https://www.pivotaltracker.com/story/show/99310600)
Sets the ELB ingress rule to only allow connections from the given
IPs/CIDR ranges. Defaults to 0.0.0.0/0 in vars/common.
Overwriting the `user_ips` list in user.yml allows limiting access
to full preview/staging environments.
Creates a separate ingress resource for each developer IP/CIDR range.
Requires:

User IPs ingress for www ELB

---

cloudformation_templates/aws_nginx.json
playbooks/roles/nginx/templates/assets.j2
stacks.yml
vars/common.yml

Maps assets /g-cloud-7 prefix to the G7 draft documents bucket.
This makes it possible to use the assets domain for draft documents
as well as any framework related files (eg supplier pack) as long as
the S3 object path starts with "g-cloud-7" prefix.

Proxy g-cloud-7 assets to the draft documents bucket

---

stacks.yml

The supplier app uses [`DM_CLARIFICATION_QUESTION_EMAIL`](https://github.com/alphagov/digitalmarketplace-supplier-frontend/search?utf8=%E2%9C%93&q=DM_CLARIFICATION_QUESTION_EMAIL) to set an email address where to send clarification questions.

Add clarification_question_email variable

---

cloudformation_templates/aws_monitoring.json

This will create a CloudWatch metric filter that takes the requestTime from Nginx JSON logs and puts it into a CloudWatch metric. In preview the metric will have a namespace preview-preview/Nginx and a name of requestTime. This doesn't match metric naming convention we've used to date because we don't have access to the ElasticBeanstalk environment name. This may actually turn out to be a more flexible naming convention.
This has been tested on preview

Add a CloudWatch metric for Nginx requestTime

---

playbooks/roles/nginx/templates/api.j2
playbooks/roles/nginx/templates/nginx.conf.j2
playbooks/roles/nginx/templates/www.j2
vars/common.yml

$http_dm_request_id takes the value from the request header however we
want to take it from the response of the upstream.
http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_http_
The way that we pass the DM-Request-ID around services is through the HTTP header. As a result, a client could set the DM-Request-ID themselves from outside. This strips that header on the way in so that one is generated internally.
There is no unset header directive, instead an empty value prevents the header being passed on to the proxied server.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

DM-Request-ID updates for Nginx logs

---

vars/common.yml

This includes this change
https://github.com/alphagov/digitalmarketplace-aws/commit/6fd5554f3092220692044212bfec37f9f787fbe3
When rebasing I accidentally lost the AMI bump.

Bump Nginx AMI

---

cloudformation_templates/alarms/CloudWatchHTTP5xxCountAlarm.j2
cloudformation_templates/alarms/HTTP5xxCountAlarm.j2
cloudformation_templates/alarms/LoginFailurePercentAlarm.j2
cloudformation_templates/alarms/base_alarm.j2
cloudformation_templates/app_base.j2
cloudformation_templates/aws_digitalmarketplace_supplier_frontend.json
cloudformation_templates/metrics.j2
dmaws/cloudformation.py
stacks.yml

This has been tested on preview and can be seen in the CloudWatch console. Select the `preview-preview/api` metric in the Custom Metrics drop down on the left.
Move the 5xx metric filters and alarms into dmaws from the applications .ebextensions.
A short version of the application name has been added to the `DM_METRICS_NAMESPACE` to match the namespace used for Nginx logs and be easier to search for than making the metric names themselves really long. This is the AWS recommended way of organising metrics. For example, the metrics namespace for the supplier app in preview would be `preview-preview/supplier-frontend`.
Metric filters and alarms have been pulled out into macros to avoid mistakes in boilerplate such as log group name, alarm actions and namespace.
The metric filter macro …

Move cloudwatch to dmaws

---

cloudformation_templates/alarms/HTTP5xxCountAlarm.j2
cloudformation_templates/aws_digitalmarketplace_admin_frontend.json

Sphinx doesn't support anchors starting with digits for some reason.
This is a direct copy of the login failure metric and alarm used for supplier frontend.

More metric filter fixes

---

cloudformation_templates/aws_jenkins.json
cloudformation_templates/aws_route53_root_records.json
dmaws/cli.py
packer_templates/jenkins.json
stacks.yml
vars/ci.yml
vars/common.yml

This pull request: 
- sets up a Jenkins instance with a 20Gb EBS drive on digitalmarketplace-development
- whitelists Aviation House IP addresses
- adds a DNS record at [https://jenkins.development.digitalmarketplace.service.gov.uk/](https://jenkins.development.digitalmarketplace.service.gov.uk/)
- assigns it an [Elastic IP address](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html)

Add configuration for a Jenkins instance on AWS 

---

cloudformation_templates/aws_jenkins.json

The ElasticIP is an IP address and therefore the DNS record should be an
A record rather than a CNAME.

Change Jenkins Route53 record to A

---

playbooks/roles/nginx/templates/nginx.conf.j2

server tokens set to off to hide nginx verison.
Required for pen test

Set server tokens to off to hide version

---

scripts/find_slow_routes.py

This is a pretty hacky script that downloads a week's worth of logs from
CloudWatch and then tries to find the 90th percentile of slowest routes.

Add a script to find slow routes from CloudWatch logs

---

stacks.yml

Required for this to send things to the right email address: https://www.pivotaltracker.com/story/show/103088520
It's supposed to pull in this address from credentials: https://github.gds/gds/digitalmarketplace-credentials/blob/master/dmaws-vars-files/preview.yml#L47

Add G7 post-clarification email address

---

cloudformation_templates/aws_jenkins.json
vars/ci.yml

We need more memory, the OOM killer keeps killing Jenkins.
This prevents the stack running again once you've terminated the instance (because CloudFormation cannot stop it anymore).

Update jenkins box

---

dmaws/commands/release.py
dmaws/context.py
scripts/jenkins-release.sh
setup.cfg

If release-name is not set when calling release to staging current
preview release version will be used. This should act similar to the
current production releases.
"release-name" is kept as a parameter and will be used when set. Staging
is the only stage that allows an explicit release name right now, so
this is required for rollbacks (rollbacks should start with staging and
can be promoted to production, preview can not be rolled back right
now).
"release-name" check is changed to `not release_name` to avoid adding
logic to the jenkins script, which will always pass `--release-name=`
for staging, but now an empty value is allowed.
Uses ctx.out to write KEY=VALUE pairs to stdout, which is redirected
by the jenkins script to a property file. Stdout is now reserved for
this output format, …

Allow promoting preview to staging by setting empty release-name

---

vars/production.yml

Supplier app reached the autoscaling limit of 5 instances.
Since we expect an increase in requests for the last days of the
G-Cloud 7 service submission, we raise the max limit and size of
EC2 instances for supplier frontend and Data API apps.
We can reduce these limits to the previous value  after the service
submission is closed.

Increase instance size and max limit for API and supplier app

---

vars/production.yml

Similar to supplier frontend and API, since nginx is on the request
route for service submission, raising the instance size.
There's one "backend connection errors" spike in nginx ELB monitoring
in the last 7 days.

Increase production nginx instance size to t2.medium

---

cloudformation_templates/app_base.j2

Smoke tests running on the hour are failing with 504 errors. This
turned out to be an issue in the current EB Apache log rotation:
> The root cause of this is that EB rotates the logs once an hour
> BUT when rotating the logs, they do a "reload" on apache rather
> than a 'graceful'. This causes connections to be dropped.
¯\_(ツ)_/¯
and should be fixed in the newer (v1.4.6 and later) stack versions.
(https://forums.aws.amazon.com/thread.jspa?messageID=625900)

Upgrade app EB solution stacks to v2.0.1

---

vars/production.yml

Instance sizes for elasticsearch and RDS were set in the credentials
repo. Moving them to aws since they're not supposed to be secret and
keeping them near the default makes it easier to understand what types
of instances we have for different parts of the environment.

Add current production instance sizes to vars file

---

vars/production.yml

`database` key was created twice, so only the second dictionary
was kept.

Fix duplicate database variable in the production vars

---

vars/production.yml

Restoring the default instance size for supplier-frontend and Data
API apps after the close of G-Cloud 7 service submissions.
Keeping the autoscaling max instance counts and the medium nginx
instances, since nginx is not autoscaled.

Restore t2.micro instance size for supplier-frontend and api

---

cloudformation_templates/app_base.j2

This alarm was only emailing us if there was more than one 5xx in a 1 minute period.

Fix 5xx alarm to catch all errors

---

stacks.yml

So that storage that apps depend on gets put in place.
Also removes the `logs_s3` stack as it's no longer needed.

Add data_storage to www

---

playbooks/roles/nginx/templates/assets.j2
vars/common.yml

We need to preserve the update times for when we list and they cannot be
manually edited.

Continue to use existing G7 draft bucket

---

cloudformation_templates/aws_route53_root_records.json

Our access to Google Webmaster Tools is no longer working. After speaking with Ash we have decided to replacing the verification code.
We are reducing the TTL to 5 minutes in case there is any problem with replacing the old verification code.
See:
- https://github.com/alphagov/digitalmarketplace-aws/pull/163
- https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/189

Update Google site verification code

---

playbooks/roles/nginx/files/robots.txt

The search results pages will be prevented from being indexed by a meta
tag on the pages themselves.
See:
- https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/189
- https://github.com/alphagov/digitalmarketplace-aws/pull/162

Allow robots to crawl search results

---

cloudformation_templates/aws_route53_root_records.json

Mandrill SPF verification doesn't recognize current SPF value.
From Route 53 docs:
> ... we no longer recommend that you create resource record sets for
> which the record type is SPF ... its use is no longer appropriate for
> SPF version 1; implementations are not to use it ... Instead of an
> SPF record, we recommend that you create a TXT record
(http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#SPFFormat)
Setting a short TTL in case we need to revert the records. DKIM
value copied from Mandrill setup instructions page:
https://mandrillapp.com/settings/sending-domains?q=digitalmarketplace

Mandrill DNS records

---

cloudformation_templates/aws_route53_root_records.json

Route53 can't create a second TXT root record resource since one
already was created by GoogleVerification resource. So instead we
just add the SPF record to the GoogleVerification resource.

Join SPF record with Google verification TXT record

---

dmaws/commands/release.py
dmaws/deploy.py
tests/conftest.py
tests/test_deploy.py

There is a limit to the number of Beanstalk application versions that you can have, this limit is 500 per account and AWS refuses to increase it stating that we should be deleting old versions.
This adds a method to prune old Beanstalk application versions by listing them and deleting any above the number to keep.
When releasing to preview or staging (the only releases that create new versions) we need to prune the old versions before we create the version.
I have not added this to the `deploy` command because that is done manually and I don't think it should have unexpected side effects.

Prune old versions

---

cloudformation_templates/aws_route53_root_records.json

Adding to existing Google and Mandrill SPF records.
(https://support.zendesk.com/hc/en-us/articles/203683886-SPF-Learn-More)

Add SPF DNS record to allow sending emails from Zendesk

---

stacks.yml

The communications bucket is required uploading communications. The
others have been added now as they will be useful soon and it's a bit
confusing to debug when it's not available.

Add bucket env variables to admin frontend

---

stacks.yml

This updates the environment variable to be the one used in the supplier app here:
https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/config.py#L49
and here:
https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/app/main/views/frameworks.py#L400
Depends on new variable name in:

Update environment variable name to the one used in the application

---

cloudformation_templates/aws_rds_database.json
stacks.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

Sets a Parameter Group on DB instances than can be used
to tweak database settings. Dynamic parameters can be
then changed without interruption.
Enables logging of queries >1000ms on preview by default.
Logging is disabled for staging and production.
**Note:** even though AWS docs state that 
> The parameter group name itself is changed immediately, but the actual parameter changes are not applied until you reboot the instance without failover. The db instance will NOT be rebooted automatically and the parameter changes will NOT be applied during the next maintenance window.
(http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html)
CloudFormation seems to have restarted the instance when this was applied to preview causing a <1 min downtime. If we decide to …

Add DB parameter group to enable slow query logging

---

cloudformation_templates/app_base.j2

> Enhanced health reporting is a feature that you can enable on your environment to allow AWS
> Elastic Beanstalk to gather additional information about resources in your environment. Elastic
> Beanstalk analyzes the information gathered to provide a better picture of overall environment
> health and aid in the identification of issues that can cause your application to become
> unavailable.
(http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced.html)

Enable enhanced health reporting for EB environments

---

vars/common.yml

There's a new stable nginx release with some security fixes related
to the resolver (which we're using to connect to application ELBs)
http://nginx.org/en/CHANGES-1.8

Update nginx AMI with nginx 1.8.1

---

cloudformation_templates/app_base.j2

> The following statement contains all of the permissions that Elastic
> Beanstalk needs to monitor environment health
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles.html#concepts-roles-service
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced-api.html

Add service role for ElasticBeanstalk health reporting

---

cloudformation_templates/app_base.j2
cloudformation_templates/aws_s3.json

Object versioning will automatically keep old file versions so
that there's less need for us to do manual copies and backups
of modified or removed documents.
Admin app sends delete requests to remove countersigned agreements,
so we need to add a permission to EB instance profile policy.

S3 versioning and EB IAM delete permission

---

stacks.yml

Currently we use different environment variable names for the Flask secret key and then override it with `os.environ` in the [root Config class](https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/config.py#L52).
This is problematic for a few reasons:
1. `SECRET_KEY` is a Flask thing and naming it something different (even
if it is more descriptive) obfuscates what it's being used for.
2. Setting it from the environment in the base class means that we
cannot set a default for it in one of the environment specific child
classes.
If we think that it is more helpful to have more descriptive names rather than stay consistent with Flask's naming than we should map the name we use to `SECRET_KEY` in `init_app`.

Provide SECRET_KEY env var for apps

---

playbooks/roles/nginx/templates/nginx.conf.j2

By default nginx only compresses text/html this change also compresses
css and javascript.

Enable gzip for css and javascript

---

vars/preview.yml
vars/production.yml
vars/staging.yml

Updates certificate name to match the new letsencryp certificate.
Letsencrypt update job will always rename the new certificate to
keep the current name, so future renewals should require no more
changes.
Removes iam_certificate_id since it appears to be unused now.

Update preview TSL certificate ARN

---

vars/production.yml
vars/staging.yml

New certificate is uploaded to IAM so we can update the nginx ELBs to use it instead of the expiring one.

Update staging and production TLS certificate

---

cloudformation_templates/aws_rds_database.json
stacks.yml
vars/common.yml

Changes the database engine version to 9.4. Major upgrades can only be done one at a time, so there's no way to move from 9.3 to 9.5 in one step. "allowMajorUpgrades" has to be set to true to apply the change.
Despite the description in the [AWS docs][1], there doesn't seem to be a way to change the DBParameterGroup Family parameter. AWS sets the resource status to 'UPDATE_COMPLETE', but the parameter group still has the old database version. And there doesn't seem to be a way to update the parameter group family using AWS CLI, so it's likely an error in the CloudFormation docs.
The updated database version however requires a matching parameter group family, so we rename the parameter group resource to force CloudFormation to replace the old group with a new one. This runs the expected …

Update RDS database to PostgreSQL 9.4

---

cloudformation_templates/aws_rds_database.json
stacks.yml
vars/common.yml
vars/production.yml

Since we expect an increase in requests for the last days of the G-Cloud 8 service submission, we raise the size of EC2 instances for supplier frontend and Data API apps.
This is the same as we did for G7 and it was all good (see Alexey's commit here: https://github.com/alphagov/digitalmarketplace-aws/commit/df1f1effc792f5d7211896e1dcd8ea8ae1609dcc)
We can reduce these to the previous value after the service submission is closed.

Increase instance size for API and supplier app

---

vars/production.yml

Service submissions are closed and the request spike is over, so we can scale down the instance sizes. We've reached the 10 instance autoscaling limit yesterday, but it's back to 3 instances for API and supplier frontend now.

Revert "Increase instance size for API and supplier app"

---

cloudformation_templates/aws_rds_database.json
stacks.yml
vars/common.yml

This re-reverts the changes made in https://github.com/alphagov/digitalmarketplace-aws/commit/6efd5d1d2748a44446e692969f47981da085395c
This upgrade has already been run on Preview and Staging.  Once the G-Cloud 8 submissions window closes we need to pick a good time to run it on Production.

Upgrade to Postgres 9.4 (again)

---

cloudformation_templates/aws_nginx.json
cloudformation_templates/aws_route53_digital_services_store.json
playbooks/roles/nginx/defaults/main.yml
playbooks/roles/nginx/templates/digitalservicesstore.j2
stacks.yml
vars/common.yml

Points [www.]digitalservicesstore.service.gov.uk to the nginx ELB
using Route53 alias records.
There's a stage check for hosted zone domain value that will make
stack creation fail on non-production environments. This is making
sure that records don't get accidentally changed to staging ELB.

DSS domain redirect

---

vars/production.yml
vars/staging.yml

Setting up a redirect for DSS means we need to have a valid
TLS certificate for the digitalservicesstore.service.gov.uk domain.
Since we're using our existing nginx instances and HTTP listeners
on the nginx ELB we can only set up one certificate per listener -
so we need a single certificate for both digitalmarketplace and DSS
domains. The added benefit of this approach is that we don't have
any SNI issues with old OS and browsers since all requests are covered
by the same certificate.
We've requested a new certificate through ACM, which allows us to
connect it with ELB listeners using our existing template.

Switch to AWS Certificate Manager certificate for DM and DSS domains

---

README.md
cloudformation_templates/aws_jenkins.json
cloudformation_templates/aws_kibana.json
cloudformation_templates/aws_lambda.json
cloudformation_templates/aws_log_subscription.json
cloudformation_templates/aws_monitoring.json
dmaws/commands/lambda.py
dmaws/stacks.py
dmaws/utils.py
lambdas/cloudwatch_logs/main.js
requirements.txt
stacks.yml

Database stack doesn't reference the monitoring output, so there's no reason to have an explicit dependency. The only connection between RDS and monitoring is the notification when a DB instance is deleted, but there's little value in them for standalone databases.
Monitoring is still required for apps, so there's no risk of accidentally skipping the stack update.
Stops the creation process if a stack fails to create. This is similar to how we stopped when a dependant stack didn't exist, but for some reason there was no similar check for creating dependencies.
Using JSONLogGroup reference to get the log group name instead of creating the name string forces cloudformation to wait until the log group resource has finished creating. Without the dependency both log group and metric creation …

Kibana log streaming

---

lambdas/cloudwatch_logs/main.js
stacks.yml

Previous filter removed logs for health check requests by looking for log events that have either a wrong `request` or wrong `url`, but exception logs don't have any of these fields, so they got filtered out too.
Changing the filter to skip events that:
* Have `request` field and field value is matching health check
URL - filters out apache-access health check logs
* Have `url` field and field value is matching health check URL -
filters out application health check logs
* Have `remoteHost` field and field value is `::1` - filters out
Apache mod_wsgi internal connection logs
Removes duplicate `@id` field, `@message` source, account `@owner` and log group fields since they're all the same for all messages.

Fix cloudwatch stream filter

---

cloudformation_templates/aws_rds_database.json
vars/common.yml

Now that 9.4 is in production we can start testing 9.5 in preview
and staging.
Version change still requires a new parameter group resource, since
CloudFormation can't change the parameter group version in-place.

Upgrade PostgreSQL to 9.5

---

vars/staging.yml

Unintentionally reset the staging database over the weekend, so
restoring from a snapshot taken this weekend to see if we get our
data back.
Our hypothesis is that we won't, but
- at least we'll know for sure
- it's an opportunity for me to try out our backup process, if
you want to call it a process
Also toyed with the idea of increasing the number of days we keep
around our backups, but that doesn't really seem like the problem
that we have.
(ie, I think the problem that we have is that we don't have an easy way for @andrewchong to create things on staging.  We shouldn't be worried about wiping out our staging database.)

Restore staging database from a snapshot

---

cloudformation_templates/aws_kibana.json
cloudformation_templates/aws_lambda.json
stacks.yml
vars/common.yml

When Kibana server is under heavy load it stops responding to lambda
requests, which makes the function wait until it's interrupted by
a timeout. Higher timeout value means the function will wait longer,
which increases the AWS bill.
Most successfull requests to Elasticsearch should complete within 5s,
so setting that as the timeout value. It could be adjusted if the
lambda monitoring shows a lot of functions being interrupted.
It looks like micro instances aren't handling the load very well,
both preview and production instances stopped processing requests
after being up for a month. Increasing the instance size to see if
it solves the problem.
Also increasing the disk size. EBS is pretty cheap for the volumes
we're using, and log indexes take up around 400Mb per day in preview
and …

Increase kibana instance size

---

cloudformation_templates/aws_route53_root_records.json

Adds a 'none' DMARC policy to digitalmarketplace.service.gov.uk to collect reports without rejecting any emails that are currently being sent.
This sets `support+dmarc-reports@` to gather aggregate reports. Not setting up an email address to gather individual failure notifications since we don't know the volume yet.
Once we start receiving daily aggregate reports (first one should arrive after 24 hours) and verify they're ok we can change the policy to `p=reject` to match the service.gov.uk one. Ideally, we'd do this before October 1st, but `p=none` should override the service.gov.uk default either way.

[#124089551] Add initial DMARC policy record to Route53 root domain

---

cloudformation_templates/aws_route53_root_records.json

Zendesk uses CNAME records for DKIM authentication and requires two
separate records to be set up.
https://support.zendesk.com/hc/en-us/articles/203663326-Digitally-signing-your-email-with-DKIM-or-DMARC
This might require a change in Zendesk configuration to enable signing
We're still using Mailchimp for non-transactional emails to buyers
and suppliers, so we need to set up email authentication for it.
http://kb.mailchimp.com/accounts/email-authentication/set-up-custom-domain-authentication-dkim-and-spf

DKIM records for Zendesk and Mailchimp

---

dmaws/cli.py
dmaws/commands/deploy.py
dmaws/commands/release.py
dmaws/github.py
requirements_for_test.txt
tests/test_github.py

Not all CLI commands require stack information, so adding a separate `base` click group. Both groups are used for the `dmaws` command.
This drops the auto environment variable support that we're not using. Only explicit variables set for options will be picked up by click.
Creates a github deployment for a given repository, ref and environment and sets the deployment status.
Requires a JSON export of Jenkins deployments and creates a Github Deployment for each build.
Adds a publish_deployment step to the release job. Requires a GITHUB_TOKEN and Jenkins build environment variables to be set.

Publish Jenkins releases to Github Deployments API

---

README.md
dmaws/cli.py
dmaws/commands/deploy.py
requirements.txt
scripts/jenkins-release.sh

There doesn't seem to be a way to organize commands with and without arguments before the command name in a single CLI, so in order to support the helper commands I'm moving the STAGE argument after the command name.
This also removes ENVIRONMENT argument. We haven't used environment names that don't match the stage name until now, and we don't have any plans to at the moment, so I'm hiding the separate argument and making sure that environment is always the same as stage.

Move stage argument after the command name

---

vars/common.yml

Preview DB is out of space.  Let's bump it up to 10GB.

Upgrade to 10GB of storage on DB instance

---

dmaws/commands/release.py

`repository_path` is the local file system path. Repository name should be parsed from the application repo URL, since it needs to contain the organization name.

Fix Github Deployments repo URL

---

vars/common.yml

Sets the API max instance count in preview and staging to 1 to stop AWS from creating a new API instance every time functional tests run.
Functional tests create enough load to trigger the scaling policy, but the newly created instance only exists for a few minutes. Setting max instances to 1 will prevent this. Initially, we set max instances to 2 for all apps expecting Elastic Beanstalk to do a zero time deploy by replacing a running instance with a new one, but that doesn't seem to be happening.
Note: this is the simplest solution I could think of. Ideally, we'd change the autoscaling triggers to stop this from happening, but that requires a bit more digging into the CloudFormation templates and essentially achieves the same thing.

Prevent API from autoscaling in preview during functional tests run

---

cloudformation_templates/aws_route53_root_records.json

We're using GMail/Google Groups to send group emails from the support email address, so we need to validate them in order to pass DMARC checks.
The DKIM record is different for each account, so it needs to be generated through Google Apps administrator page.
https://support.google.com/a/answer/173535?hl=en&ref_topic=2752442

Add Google DKIM record to digtalmarketplace.service.gov.uk DNS

---

cloudformation_templates/aws_route53_root_records.json

Route53 limits TXT records to 255 characters, so we need to split Google DKIM record into two quoted strings.
https://support.google.com/a/answer/173535?hl=en&ref_topic=2752442

Split Google DKIM record to meet TXT length limit

---

cloudformation_templates/aws_route53_root_records.json

Splitting the record in two stops it from being recognized by DKIM checkers. After some investigation it looks like the way to do it is to use 👉 a single space between two quoted strings 👈 instead of a newline. This is accepted by Route53 despite being longer than 255 characters and seems to be recognized by DKIM checking tools.
https://stelfox.net/blog/2014/07/spf-and-dkim-records-in-route-53/

Fix Google DKIM record split

---

.travis.yml
cloudformation_templates/aws_route53_root_records.json

From dmarc.org FAQ:
> Given the real-world, non-technical use of the term, quarantine means "set aside for additional processing". The definition is at the appreciation of the manager of the receiving email infrastructure. It may mean deliver to the "junk folder" but it may also mean hold in a database for further review by dedicated personnel, or simply add a specific tag to the message before delivery.
https://dmarc.org/wiki/FAQ#What_does_a_.22quarantine.22_policy_mean_in_a_DMARC_record.3F
We're going to 'quarantine' instead of 'reject' to check that Google forwarding policy changes with a strict DMARC policy.

Set DMARC policy to quarantine

---

playbooks/roles/nginx/templates/api.j2
playbooks/roles/nginx/templates/assets.j2
playbooks/roles/nginx/templates/nginx.conf.j2
playbooks/roles/nginx/templates/www.j2

proxy_set_header directives are only considered at the most deeply nested
level, so remove them all from everywhere and only define them in nginx.conf.j2

always set nginx proxy headers

---

playbooks/roles/nginx/templates/assets.j2

as S3 documentation says (http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html):
Host
> For path-style requests, the value is s3.amazonaws.com. For virtual-style
> requests, the value is BucketName.s3.amazonaws.com. For more information,
> go to Virtual Hosting in the Amazon Simple Storage Service Developer Guide.
We're setting it to $http_host in the nginx base config, which is causing S3 to
reject all our requests. So lets unset it here. Because of proxy_set_header's
silly no-inheritance rule we have to redefine the other proxy headers for
all assets endpoints.

unset Host on s3 requests

---

vars/staging.yml

DOS-2 is closed and we need some preset data to check that the scripts determining who is on the framework do the right thing.

Rollback staging database to this morning's version

---

dmaws/commands/migratedata.py
dmaws/rds.py

The data we collect has changed (grown, mostly) since this data migration logic was last used, and so we aren't removing all the real personal data that we should.  
We delete all draft things because they've never been made public and we try to remove real names and email addresses where we've asked for them:
- Draft briefs are deleted
- All framework agreements are deleted
- All brief responses are deleted
- Two more fields are added to the declaration because we need them for the updated signing flow

Clean production data for other environments

---

dmaws/rds.py

The way the query was written previously, all brief user rows were being deleted.
Seems weird because the `brief_id` column doesn't exist in the `briefs` table.
So, for example:
```sql
-- this does what we want
SELECT * FROM brief_users WHERE brief_id IN (
SELECT id FROM briefs
)
-- this throws an error because the column name is wrong (and, presumably, nowhere else in the query)
SELECT * FROM brief_users WHERE brief_id IN (
SELECT alligator FROM briefs
)
-- this selects all brief_users (which is arguably surprising/unexpected behaviour)
SELECT * FROM brief_users WHERE brief_id IN (
SELECT brief_id FROM briefs
)
```

Delete less brief_users

---

dmaws/rds.py

Once a framework is no longer open, we're allowed to see the draft services that were submitted.
<sup>(small change)</sup>

Delete draft services for open frameworks

---

cloudformation_templates/aws_s3.json
stacks.yml

Enables access logging for all S3 buckets. Logs are stored in a separate logs bucket for each environment and logs from buckets are stored in separate folders. Log bucket access logs are stored in the same bucket (which thankfully doesn't create an infinite feedback loop).
Enabling logging was recommended by ITHC report. I'm not sure what the cost implications are since it seems to create a lot of small files, and S3 could get quite expensive for LIST/PUT operations, so we'll have to keep an eye on it.

Add S3 logs bucket and enable S3 access logging

---

requirements.txt

Running the migration was causing some warning in the output:
something about not explicitly casting the right thing for bcrypt.
(seen here: https://github.com/pyca/bcrypt/issues/82#issuecomment-247816431)
The solution seems to be to upgrade bcrypt, which _looks_ scary
because it goes up a major version but actually the changelog
doesn't seem too serious.
[Changelog](https://github.com/pyca/bcrypt#changelog)

Upgrade bcrypt

---

cloudformation_templates/aws_cloudtrail.json
stacks.yml

Sets up CloudTrail to store logs in S3 bucket and creates a separate CloudWatch log group to send logs to.
gds-audit-cloudtrails S3 bucket is controlled by GDS Security Team, and they've asked us to use AWS account ID as key prefix.
CloudWatch is setup in the same AWS account as the CloudTrail, so we have access to view the history of events and can create CloudWatch alerts in the future.
There's only one CloudTrail per AWS account, so the stack name doesn't include stage or environment names (similar to Route53 stacks).
IAM policies and CloudTrail settings are taken from https://github.com/alphagov/aws-security-alarms/blob/master/terraform/main.tf
From AWS docs:
> AWS CloudTrail is a web service that records AWS API calls for your
> account and delivers log files to you. The recorded …

[#137354029] Enable CloudTrail logging to S3 and CloudWatch

---

dmaws/commands/migratedata.py
dmaws/stacks.py
tests/test_stack.py

####	Set the profile correctly for StackPlan
The `ctx.stage` value is passed in as a `profile_name` to the `RDS` initialisation, but [it doesn't get passed properly to the `StackPlan`](https://github.com/alphagov/digitalmarketplace-aws/blob/master/dmaws/commands/migratedata.py#L38-L39).  Added an extra bit to the `from_ctx()` method that fixes this.
The way I understand it, we've been creating a security group for our new `exportdata` instance (which lets Jenkins connect to the database) and then attaching it to the target stage (where we're going to import the data) as well so that Jenkins can pg_dump to the target database.
Reusing our new security group this way has occasionally meant -- if the script fails to clean up everything -- we leave open access to our target database which …

Pass in correct profile to the StackPlan + open `database_dev_access` for target stage

---

dmaws/build.py
dmaws/commands/migratedata.py
dmaws/rds.py
dmaws/utils.py
tests/conftest.py
tests/test_build.py
tests/test_utils.py

Instead of streaming our `pg_dump` output straight into the target database, this code creates an intermediary `exportdata.sql` file in a particular directory.
The (relative) filepath is a new parameter passed into the `migratedata` command, and then the python code will create the directory structure and dump the .sql file into it before importing it into our target database.
We're relying on [the migratadata `-jenkins` job](https://github.gds/gds/digitalmarketplace-jenkins/pull/73) to do the sync, and then do the cleanup.
We can decide either to do or not do the 'export to a file' part of this based on whether or not we pass in a filepath. Tested locally and both work.

Dump exportdata into a local directory

---

vars/production.yml

When downloading lists of users from the API we have seen our instances run out of memory. This should resolve that problem.

Bump API model to t2.medium as larger memory required

---

terraform/modules/iam-users/infrastructure.tf
terraform/modules/iam-users/variables.tf
terraform/root/aws-dm/main.tf
terraform/root/aws-dm/variables.tf

This PR adds two news groups:
- DevInfrastructure: users who can assume the infrastructure role in the dev account
- ProdInfrastructure: users who can assume the infrastructure role in the dev/prod accounts

Add dev and prod infrastructure user groups

---

.gitignore
Makefile
dmaws/commands/paasmanifest.py
paas/manifest.j2
paas/run.sh
requirements.txt
terraform/modules/aws-env/main.tf
terraform/modules/jenkins/iam.tf
terraform/modules/paas/iam.tf
terraform/root/aws-dm/.gitignore
vars/common.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

I added a new command to dmaws to generate PaaS manifest files from a Jinja2 template. The command is using the built-in variable loading mechanism.
Subcommand: paas-manifest
Extra options:
```
-t, --template PATH             Manifest Jinja2 template file
-c, --credentials-repo PATH     Path to the digitalmarketplace-credentials
repository
-o, --out-file TEXT             Output file, if empty the template content
is printed to the stdout
```
Components:
- Paas manifest Jinja2 template: paas/manifest.j2. Can be changed with the --template option.
- The PaaS configs are added to the existing apps under the paas key (see vars/common.yml)
- Application secrets are optional and loaded the same way but from the credentials repo (vars/common.yaml and vars/[environment].yaml)
The configurations …

[preview] Add paas-manifest command to dmaws for generating PaaS manifest files

---

Makefile
dmaws/commands/release.py

We're running PaaS deployments in parallel with existing EB ones at the moment, and they're creating the same release-* tags. Which means we can no longer depend on the EB application version existing when the tag exists. Since we don't have a way to check that EB version exists, we ignore any errors instead and force the tag push.
Should make it easier to see what release was being deployed and can help avoid any accidental clashes for failed cleanup.
RELEASE_NAME contains the full tag/archive name with the "release-" prefix, so we don't need to add it in the make step.

Release tag for paas jobs

---

Makefile
scripts/paas_populate_db.sh

We need to set up an ssh tunnel via the api app to allow importing of
data into the PaaS db's from a local dump.
The `PAAS_SPACE` needs to be provided as a parameter which is checked
against the currently targeted cf stage to prevent accidental writing to
the wrong db.

Add Make rule to populate PaaS db from dump

---

cloudformation_templates/aws_nginx.json
playbooks/roles/nginx/defaults/main.yml
playbooks/roles/nginx/files/maintenance.html
playbooks/roles/nginx/tasks/main.yml
playbooks/roles/nginx/templates/maintenance.j2
terraform/environments/preview/main.tf
terraform/environments/preview/variables.tf
terraform/environments/staging/main.tf
terraform/environments/staging/variables.tf
terraform/modules/nginx/autoscaling.tf
terraform/modules/nginx/elb.tf
terraform/modules/nginx/variables.tf

Doesn't seem to have a Pivotal Story, but this is connected [https://www.pivotaltracker.com/story/show/143486469](https://www.pivotaltracker.com/story/show/143486469).
We don't currently have a way to switch the site to a maintenance mode if we have planned down time.
If the `nginx_config` variable is set to `live` in Terraform for a particular environment the site will behave as usual. If it is set to `maintenance` then Ansible will update the Nginx autoscaling group and only load up the maintenance and healthcheck nginx configs.
The healthcheck config allows the ELB healthchecks to pass, and the maintenance config returns a static html file for any url on the www subdomain. This html file needs updating once content and design have looked at it.

Add terraform/ansible/nginx setup to enable maintenance mode

---

paas/manifest.j2

Since admin and supplier apps server their status endpoint from /admin/_status and /suppliers/_status we need to add the path prefix to the health check URL

Fix admin and supplier frontend PaaS healthcheck path

---

Makefile
paas/manifest.j2

Updates `cf push` commands to set the docker container name when
deploying an app.
Removes command from the manifest so that it doesn't override the
docker container ENTRYPOINT.
Removes build-app, download-deployment-zip and DEPLOYMENT_DIR
related code.

Use cf push to deploy docker images instead of local directories

---

Makefile

We don't need the DB migration app to run continuously, since we're
pushing it before we run the migration task. So as long as the task
completes within the sleep period we can shut down the instance
afterwards.
2h should be more than enough to run the DB migration.

Replace DB migration `inifnity` sleep with `2h`

---

Makefile
paas/manifest.j2

Setting 'stack' in the manifest makes `cf push` raise an error
(The app is invalid: Lifecycle type cannot be changed) when pushing
to a docker app that already exists.
Removing 'stack' solves the issue.
Docker app images copy the application files to /app, but the
working directory is not set when SSH-ing into the instance or
running the CF task, so we need to specify the full path.

Fix docker db migration

---

Makefile

When running application.py from outside /app the task fails when
trying to load the schemas. Instead, we cd into the APP_DIR before
running `db upgrade`.

Fix migration task failing to load JSON schemas

---

terraform/environments/preview/main.tf
terraform/environments/production/main.tf
terraform/environments/staging/main.tf
terraform/modules/application-logs/main.tf
terraform/modules/application-logs/variables.tf

Trello: https://trello.com/c/FtoKj86m
When the apps are running in the PaaS, they'll produce application logs and nginx logs. We need to capture these in CloudWatch in separate log groups to aide in processing them.
This sets up the log groups in Terraform. Prod logs need to be kept for at least 10 years.

Set up log groups for PaaS apps

---

playbooks/roles/nginx/files/maintenance.html

Adding a maintenance page template that looks like [our 404 page](https://www.digitalmarketplace.service.gov.uk/sponge-avengers).
Started with the 404 page HTML and then made a bunch of small changes.  [Second commit](https://github.com/alphagov/digitalmarketplace-aws/commit/7ba21c061563f4a42a2371d62000f4a71429d38c) is probably the most interesting one. Also did some magic behind the scenes to crunch down all that CSS, but it's still gonna weigh in at ~2000 lines.  (aside: our reset CSS rules are repeated 8(!) times in our compiled `application.css`. 😱 ) 
@tracy-content's had a look at this, so I've removed the `WIP`.
I've created a repository that does all of the CSS munging.  If you want to update the maintenance page or create more static pages with our Digital Marketplace styles, it's …

🏀  Baller maintenance page 🏀 

---

paas/search-api.j2

production.marketplace.team domain will not exist after the switch,
so we need to point the search api to the elasticsearch using the
actual production service domain.

Fix production DM_ELASTICSEARCH_URL

---

terraform/environments/production/main.tf
terraform/modules/elasticsearch/autoscaling.tf
terraform/modules/nginx/autoscaling.tf

The production state file has been updated in S3 so that the nginx route53 zone being managed by Terraform is now the original digitalmarketplace.service.gov.uk zone. This is so that when we make the switch from production.marketplace.team, we don't need to recreate the zone file and lose the name server records.
The domain is updated here to match the new zone file. The original subdomain records for api, assets etc will need to be deleted before this is applied so that Terraform can recreate them.

Change production domain to digitalmarketplace.service.gov.uk

---

paas/admin-frontend.j2
terraform/environments/production/main.tf

user_ips are set in common credential variables since they're the
same for all environments apart from production.
We could override the value with the production variable file, but
it making production explicitly set 0.0.0.0/0 as allowed IPs seems
more straightforward and less prone to error if the config file
load order changes for some reason.

Open production environment for all IPs

---

vars/production.yml

This matches the average number of production instances we had on
the AWS environment over the last month.

Change PaaS production instance counts to 5 per app

---

terraform/modules/log-streaming/lambda.tf

`paths.module` will use a local path, meaning that terraform will try
and change the path depending on who's local environment is being used.
Using local paths fixes that.

Use relative paths instead of `paths.module`

---

terraform/environments/production/main.tf

To match the existing production nginx sizes.

Increase production nginx instance sizes to t2.medium

---

playbooks/roles/nginx/templates/assets.j2

"Page not found" layout for the failed assets. requests is served
from the buyer frontend, which means we need to set the auth headers
when sending the request to the CloudFoundry app.

Set the basic auth header when requesting the assets 404 page

---

vars/production.yml
vars/staging.yml

Some requests (eg framework suppliers list) get killed by uwsgi
master process when running with the 512m limit.
This brings the instance sizes closer to what we're running in
production at the moment before we can investigate the issue
further.

Set PaaS api instance memory limit to 1024m

---

Makefile

With a finite sleep command db migration app keeps restarting every
N hours.
Since the CF tasks spin up a new container for the task we don't
need any application instances to keep running once the code is
pushed, we're only using the db migration app as the source of
configuration and container data.
So we should be able to stop it before running the task.

Stop db migration app before running the task

---

playbooks/roles/nginx/defaults/main.yml

Without adding the elasticsearch config we lose the connection from search-api to elasticsearch when in maintenance mode.

Add elasticsearch nginx config to maintenance mode

---

playbooks/roles/cloudwatch/templates/nginx_awslogs.conf.j2
playbooks/roles/nginx/templates/nginx.conf.j2
terraform/modules/nginx/autoscaling.tf
terraform/modules/nginx/main.tf

We're not storing plaintext logs for any of the other app logs, so
we can remove them from nginx as well.
JSON logs have the same data, are streamed to Kibana  and are stored
in CloudWatch for 10 years now.

Remove nginx plaintext log group

---

vars/production.yml

Getting a list of framework suppliers seems to run into the memory
limits on production.

Bump production API instance size to 2GB

---

dmaws/rds.py

This will mean our email addresses for our users can be added to mailchimp lists. This is important so we can run scripts that add users to mailchimp lists on our preview and staging environments.
We can no longer use @example.com to do this because mailchimp does not allow emails with this domain to be added as it affects its delivery rate (the same reason you can not subscribe a google
group to a mailchimp list under the group email).
Related trello story where we wish to add user emails to mailchimp lists: https://trello.com/c/XOCeuOYW/254-update-mailchimp-user-list-everyday

User email domain change to `marketplace.team`

---

terraform/accounts/main/route53.tf
terraform/accounts/main/variables.tf

Moves away from the beta service domain that's not managed by
Terraform.

Add a ci.marketplace.team DNS record for the Jenkins instance

---

scripts/clean_docker_images.sh
terraform/modules/iam-common/packer.tf
terraform/modules/jenkins/iam.tf

As part of the process of cleaning up old AMIs, we need to delete the
snapshot that is created.
To automate the process of cleaning up AMI images, Jenkins should be
able to assume the packer role.

Let Jenkins assume packer role

---

vars/preview.yml
vars/staging.yml

Downloading the buyers user list from the admin app is still breaking
on preview and staging. Bumping to match production where it works.

Bump preview and staging api memory to 2GB

---

terraform/accounts/main/route53.tf

Production domain was temporary during the PaaS switch and is no
longer used.

Remove NS record for production.marketplace.team

---

terraform/environments/preview/main.tf
terraform/environments/preview/variables.tf
terraform/environments/production/main.tf
terraform/environments/production/variables.tf
terraform/environments/staging/main.tf
terraform/environments/staging/variables.tf
terraform/modules/log-streaming/lambda.tf
terraform/modules/log-streaming/src/main.js
terraform/modules/log-streaming/variables.tf

Removes AWS Elasitcsearch permissions and request signing logic from
the function and adds authenticaton header for Logit Elasticsearch.
Nested keys in log message fields are causing issues with Kibana,
especially when the field type changes between messages. Eg api_error
can be both a string message or a dictionary, which isn't valid in
Elasticsearch index mapping.
Since we don't use the nested keys for searching and filtering and
and having them mapped creates issues with log streaming we can
serialize them to JSON strings in the streaming Lambda function.
All nested objects and arrays are serialized.

Logit streaming

---

terraform/modules/log-streaming/lambda.tf

We've seen some occasional (a few per day) timeouts on the log
streaming lambda functions likely caused by slow Elasticsearch
responses.
Raising the timeout value from 5s to 10s might help reduce the number
of failed runs. We don't want a very high timeout value since if
Elasticsearch at any point starts to respond to requests very slowly
our functions will spend more time waiting which can very quickly
raise the AWS Lambda costs.

Raise log streaming lambda function timeout to 10s

---

.gitignore
README.md
kibana/Makefile
kibana/package.json

`make dump STAGE=...` downloads Kibana index from a specified stage stack
and stores the output in `kibana-export.json`.
`make restore STAGE=...` replaces target stack Kibana index with data
from `kibana-export.json`.

Add make steps to dump and restore Kibana configuration

---

paas/briefs-frontend.j2
playbooks/roles/nginx/templates/assets.j2
playbooks/roles/nginx/templates/www.j2
terraform/environments/preview/main.tf
terraform/environments/preview/variables.tf
terraform/modules/nginx/autoscaling.tf
terraform/modules/nginx/variables.tf
vars/common.yml

PaaS is handling routing for specific frontend apps. This means that
from nginx we can just pass all traffic to a single frontend url.
We keep the rule for /admin so we can firewall certain ips.
The subdomain being used is different from the other front end apps so
that the app doesn't immediately get traffic. We'll want to get the app
up and running before we send traffic to it.
The briefs frontend won't need search api details, so we drop them from
the template.

Add briefs frontend

---

terraform/environments/production/main.tf
terraform/environments/production/variables.tf
terraform/environments/staging/main.tf
terraform/environments/staging/variables.tf

Like preview, we can consolidate the frontend urls we give to nginx as
the routing is handled by PaaS.

Consolidate frontend urls on staging and production

---

playbooks/roles/nginx/templates/_macros.j2

Our nginx configuration sets HSTS header for all requests
apart from the health checks coming from the ELB.
At the same time, our downstream application servers hosted on PaaS
are returning another HSTS header set by Cloud Foundry router.
The combination of `proxy_pass` and `add_header` makes nginx return
two HSTS headers to the client (our one and CF one), which is invalid.
CF header applies to the cloudapps.digital domain and while it's
unlikely to be removed it shouldn't affect our approach to HSTS for
our own domains. So we're removing the downstream header and are only
passing our own `add_header` to the client.

Don't pass downstream HSTS header to the client

---

terraform/modules/log-streaming/src/main.js

`typeof null === 'object'`, so some of the None values were being
converted to `"null"` when trying to stringify nested objects.
This causes an error for numerical fields, since `"null"` is not
a valid value.

Don't convert nulls to strings in the log streaming lambda

---

vars/common.yml

The briefs subdomain was set to `dm-briefs` so the new app could be
released without receiving traffic straight away so we could ensure it
worked properly without breaking the buyer frontend.
Now that we've tested it, we can change the subdomain here so subsequent
releases are assigned the correct subdomain.

Set briefs subdomain to `dm`

---

terraform/environments/production/main.tf
terraform/environments/staging/main.tf

Similarly to how we added the briefs log groups to preview, which
required splitting the log groups types to avoid Terraform weirdness
(see previous commits), we add them here to staging and prod.

Add briefs log groups for staging and production

---

vars/preview.yml

For the duration of the exercise we're raising the instance counts
to 3.

Raise preview PaaS instance counts to 3 per app for the game day

---

vars/preview.yml

We took the instance counts on PaaS up to 3 for the game day so that
preview would be closer to production.
Removing the specification for the number of instances here will set it
to its default of one.

Bump preview instance count back to one

---

README.md
terraform/README.md

During the game day, we found that the Terraform instructions were a little hard to find as they were buried in a separate README. 
This PR adds some links to specific parts of the README, which will hopefully make them stand out more when skim reading.
Also includes some minor formatting changes.

Terraform README updates

---

terraform/accounts/main/s3_buckets.tf

MFA delete for s3 buckets can only be turned on by the account root
user, and only via the command line. It can't be done via terraform.
It's already been turned on by the above method manually. This means
that without now adding it to the terraform config, terraform will want
to turn it off every time you plan or apply, even though it can't.

Set mfa delete on for db backups bucket

---

.travis.yml
Makefile
requirements-dev.txt

Updates pytest to work with python 3.6 and renames dev requirements
file to match the file name in app repos.

Update travis python version to 3.6

---

paas/brief-responses-frontend.j2
terraform/modules/application-logs/variables.tf
vars/common.yml

Adding the new app to the list in the application logs module will
create the log groups as well as the metrics.
This sets the domain and the path for the new app when deployed to PaaS.

Add brief responses frontend

---

paas/brief-responses-frontend.j2

When templated by Jinja the first line was treated as a list and
indented.
The extra line prevents this.

Fix formating error with brief-responses yaml

---

paas/brief-responses-frontend.j2

The aws-logs agent needs creds to send logs to cloudwatch

Add aws creds to brief-responses manifest

---

paas/_base.j2
scripts/unmap-route.sh
vars/common.yml

Adds routing so that buyer-frontend will receive anything that goes to `/buyers/direct-award` and also be the fallback for un-routed urls at `/`. Tweaks templating to allow multiple paths to be supplied. The first path specified in `common.yml` against the app will be the one used for the healthcheck. Not sure if this is preferrable to explicitly adding another key called e.g. `healthcheck_endpoint`, but will leave that open to review.
Also not sure what you do so far as testing, but I didn't see anything pre-existing to edit or add to. Did I just miss it, or is it in another repo, or..?
https://trello.com/c/Hlq5mzAy/619-save-a-search-and-create-a-project

Add routing for direct-award on buyer-frontend

---

scripts/unmap-route.sh

There was one too many 'done's. Now there is just one.

Fix typo with unmap-route script

---

paas/user-frontend.j2
terraform/modules/application-logs/variables.tf
vars/common.yml

Adds user-frontend to the Terraform apps list to create
log groups and monitoring metrics.
Sets up a manifest template for PaaS deployments.

Add user-frontend app to Terraform and PaaS

---

scripts/generate-bcrypt-hashed-password.py

generate-bcrypt-hashed-password raises an error on python3 since `bytes` is called without an encoding argument. Replacing it with `.encode` should fix the problem.

Fix "string argument without an encoding" python3 error in bcrypt script

---

scripts/clean-db-dump.sql

Currently, if any of the SQL commands in the clean DB dump script
fail to apply psql will ignore the error and continue, existing with
a 0 status in the end. This could result in DB dumps that still
contain personal data if eg there's a syntax error in one of the
clean-up commands.
ON_ERROR_STOP will terminate psql and exit with a non-zero status if
any of the SQL commands return with an error.

Fix signed agreements cleanup

---

paas/user-frontend.j2

Reset password emails are being switched to use Notify in
alphagov/digitalmarketplace-user-frontend#10 so it'll need new
environment variables.
This PR has to be merged immediately before the user-frontend one.

Replace Mandrill API key with Notify for user-frontend

---

paas/briefs-frontend.j2
paas/supplier-frontend.j2

The briefs and supplier frontends are going to send user create/invite
emails with notify, hence the need for the notify api key.
Briefs frontend will only use notify so we can drop the mandrill key.
Supplier frontend will still use both.

Add notify api key to briefs and supplier frontends

---

paas/admin-frontend.j2

The admin apps sends emails to invite supplier contributors. It used to
use Mandrill, now it uses Notify.

Replace mandrill with notify api key for admin

---

grafana/dm-apps.json

Add brief-responses-frontend and user-frontend to grafana apps.
https://trello.com/c/lAZgnrSn/19-add-brief-responses-frontend-and-user-frontend-to-grafana

Add brief-responses-frontend and user-frontend to grafana apps

---

terraform/modules/log-streaming/src/main.js

Add the instance ID (from payload.logStream) to log entries in Kibana to help troubleshoot possible errors with specific app instances
https://trello.com/c/RWkQeJE3/22-add-paas-instance-ids-to-kibana-logs

Add new field to Kibana log streamer

---

vars/production.yml

Reviewing monitoring for the last week, our user-frontend and admin-frontend barely hit 2% CPU. Let's scale down the default number of instances we create for these apps.

Downscale user-frontend and admin-frontend apps

---

Makefile
paas/_base.j2
paas/router.j2
scripts/unmap-route.sh
vars/common.yml

By default, make prints the command being executed, so when the output of generate-manifest is being redirected to a file the resulting manifest contains the command names before the YAML front matter.
Adding `@` stops make from printing the commands, but keeps the command output.
Changes the base manifest template to include application routes as-is (only formatting them to add current environment) instead of constructing the route from domain / subdomain and paths.
This allows us to specify multiple subdomains / domains per app, and specify manifests for apps that don't need a route.
To avoid duplicating the application paths between environments we format routes with the current environment, so they can be specified once in the common vars file.
PaaS now allows us to add custom domains …

Preview paas router manifest

---

vars/common.yml

cdn-route doesn't support binding to an app. It doesn't provide
any service variables to the application, and since traffic is
routed based on the application domain there's no need to bind it
to the app.

Don't bind cdn-route service to the router app

---

paas/_base.j2

As Jinja is in `StrictUndefined` mode, the only function that
can be called on an undefined object is the `defined` function.
Therefore we make sure that we don't try to access `routes`
unless we are sure it is defined.

Allow undefinition of 'routes' variable

---

vars/production.yml

Production doesn't follow the `*.{env}.marketplace.team` domain
pattern, so we need to set the domains explicitly.
This also scales router app to 3 instances from the production default
of 5. Nginx is pretty fast and additional instances would reduce cache
hits for any pages or assets cached by nginx.

Add correct production domains to router app

---

terraform/modules/log-metrics/main.tf

Since we're using the same application dashboard for applications
and router the metric names need to match.
Application 500s use {app_name}-nginx-500s, so we need to rename
router metric from router-500s to router-nginx-500s. This metric
is already being picked up by the cloudwatch-to-graphite app.

Fix router 500s metric name to match application ones

---

terraform/environments/preview/variables.tf
terraform/environments/production/variables.tf
terraform/environments/staging/variables.tf

Maintenance mode is now turned on by using paas manifests rather
than AWS ngxin groups after the move to the PaaS router.
This commit removes some left over references to maintenance mode
in our terraform set up.

Remove remnants of old way of turning on maintenance mode

---

terraform/modules/jenkins/iam.tf

2nd line Trello card: https://trello.com/c/f19CB6rO/102-fix-terraform-warning
While running 'make plan' the following warning is shown:
```
module.jenkins.aws_iam_instance_profile.jenkins: "roles": [DEPRECATED] Use `role` instead. Only a single role can be passed to an IAM Instance Profile
```
This change to 'role' instead of 'roles' and passing a single value instead of a list makes the warning go away.

Fix warning during terraform plan - 'roles' key is deprecated.

---

grafana/dm-apps.json
grafana/dm-overview.json
scripts/create-hosted-graphite-dashboards.py
terraform/environments/preview/main.tf
terraform/environments/production/main.tf
terraform/environments/staging/main.tf
terraform/modules/log-metrics/main.tf
terraform/modules/log-streaming/subscriptions.tf

We want to start rate limiting IP addresses due to notable incidents of very high traffic from particular IPs causing us to exceed the daily storage limit on our loggit stacks.
IP rate limiting at our nginx router will generate nginx access logs, which will still clutter Kibana and use storage space - exactly what we're trying to avoid. The long term plan is to _not_ send these logs to Kibana from Cloudwatch. We _will_ still want visibility on the number of 429's (rate limited responses) we're returning however. We can do this my sending a metric to Hosted Graphite and displaying it on our dashboard, as well as setting up alerting on it.
Originally this PR was going to filter the 429's from being sent to Loggit, but we decided that for the time being we would send them, so we have better …

Add 429 metric filter and update Grafana overview dashboard

---

grafana/dm-apps.json
terraform/modules/log-metrics/main.tf

Now that we're using `sum` rather than `samplecount` in our Hosted
Graphite setup, we can start sending a default value for log metrics.
The default value will be set for a metric if the metric filter pattern
can't be found in any of the logs. As a note, if there are NO logs for
the period, then no metric will be recorded.

Set log-metric default values to 0

---

vars/metric-exporter.yaml

We deploy a paas metric exporter app -
https://github.com/alphagov/paas-metric-exporter - on to the paas.
As part of this we must provide environment variables for the
metric exporter app such as config and credentials. This new
file stores stores all the extra configuration we need plus
gaps for credentials which are also required for deployment. Either
a developer can manually copy these into the paas-metric-exporter
manifest or they can be set using the Cloud Foundry CLI.
Note, credentials have been left with dummy vars so a developer
will need to find these credentials for deployment. I did not go
to the trouble of building a templating solution which will pull
them in from the credentials repo because it is very rare we will
need to deploy the application and I believe our current …

Add extra environment variables required for metric-exporter app

---

scripts/apply-cleaned-db-to-target.sh

This week's re-index of staging failed because the week before also failed, leaving a 'dumps' directory around. When the script came to create the 'dumps' directory again with `mkdir dumps`, it broke the whole pipeline. By adding the `-p` flag, `mkdir` will ignore directories that already exist and allow the script to continue.

Ignore mkdir error

---

vars/metric-exporter.yml

To save on our limit of metrics that Hosted Graphite can store,
we will only ship PaaS application metrics that we are actually
using in Hosted Graphite. This will save us lots of unused metrics
such as `requests` and `responseTime` that we are not using.
https://github.com/alphagov/paas-metric-exporter#metric-whitelist

Add metric whitelist so we only ship metrics we use

---

README.md
scripts/create-hosted-graphite-alerts.py

https://trello.com/c/tZghClQt/354-add-a-hosted-graphite-alert-for-missing-logs
We want to know if our logging infrastructure breaks. We can do
this by monitoring AWS `incomingLogEvents` metrics. If no logs
are being added to AWS Cloudwatch log groups for a period of time
then we can trigger an alert.
Note, we looked into setting these up as AWS Cloudwatch alerts
but ended up not going down that path. This was because
- it would be another type of infrastructure to use
- slack alerts would be extra work to set up than emails which
differs from our current alerts
- terraform doesn't let you set up cloudwatch alerts that go to
an email address (email is an unsupported protocol as described
https://www.terraform.io/docs/providers/aws/r/sns_topic_subscription.html)
unless the email alert is …

Add script to create missing log alerts in Hosted Graphite

---

paas/_base.j2

Bump instance sizes to 2G as we are getting 500s on buyer-frontend due to disk full. This will need further work from 2ndline and should only be considered a stopgap measure.
https://trello.com/c/hWPgbVc8/210

Bump instance size

---

terraform/accounts/development/main.tf
terraform/accounts/main/main.tf
terraform/accounts/main/route53.tf
terraform/accounts/main/variables.tf
terraform/accounts/production/main.tf
terraform/environments/preview/main.tf
terraform/environments/production/main.tf
terraform/environments/staging/main.tf
terraform/modules/jenkins/ec2.tf
terraform/modules/jenkins/outputs.tf
terraform/modules/jenkins/variables.tf
terraform/modules/log-streaming/subscriptions.tf

This adds the Terraform code to spin up a new instance for a new Jenkins
box. This is being done to allow pen testers to test a Jenkins instance
that isn't our actual instance. It will be provisioned via Ansiible to
be a similar as we can get it.
This Terraform code uses the existing security group that is applied to
our current box, and the same instance profile.
There is an extra security group applied, which is to allow access to
the box from Cyberis's IP's.
This could lay the groundwork for a new, upgraded Jenkins box which
could be built in the future. Alternatively, this Terraform could be
scrapped and we could move Jenkins to the PaaS.

Add Jenkins_2

---

default.nix

Please people, stop blindly bumping your terraform versions. This is getting tiring. Can we settle on 0.11.2 for a while maybe?

default.nix: bump terraform to 0.11.3

---

scripts/clean-db-dump.sql

Currently all BriefResponses are dropped during the DB sanitisation, to prevent identifying suppliers involved in an ongoing procurement.
However if the BriefResponse has an 'awarded' status, the procurement has by definition ended. It's useful to have this award data in the dev environments so don't delete it during the DB clean.

Only drop BriefResponses during DB clean if procurement is ongoing

---

terraform/modules/iam-common/common_policies.tf

I have a new phone and I can't change my MFA in the console as it needs
me to disable my existing MFA before I can, presumably, setup my new
one. So everyone needs permission to disable their own MFA.

Allow disabling MFA

---

Makefile

Ensure the RELEASE_NAME environment variable is set when deploying an
app via CloudFoundry.

Check for release name

---

vars/staging.yml

We want to run some load tests against staging. We should have matching
instance counts/sizes between staging and prod for this.

Increase staging instance counts to match prod

---

terraform/modules/iam-users/users/main.tf

We recently ran into a problem when trying to remove an IAM user.
It would complain that terraform couldn't remove the user because
they had existing login-profiles that needed to be deleted first.
This may be because login profiles were set up manually.
The solution to this is for our users to be marked as `force_destroy`
so that if we choose to delete them, terraform will also destroy
any of their related login profiles and keys.
https://www.terraform.io/docs/providers/aws/r/iam_user.html#force_destroy
https://github.com/hashicorp/terraform/issues/5908

Force destroy IAM users if we delete them

---

.flake8
Makefile
dmaws/hosted_graphite/create_alerts.py
dmaws/hosted_graphite/create_dashboards.py
scripts/create-hosted-graphite-alerts.py
scripts/create-hosted-graphite-dashboards.py
tests/test_hosted_graphite_scripts.py

Changes the missing log alert threshold from 10 minutes to 15 minutes.
While looking at this, I realised a) I didn't fully understand the Hosted Graphite scripts b) the only way to test them was to actually run them for real. So I wrote some tests! This meant moving most of their code into new modules within the `dmaws` folder (the top level scripts remain where they are, so the paths won't have changed).
Also there was no `make requirements-dev` command for this repo, so I added one 👼

Update metric alert timing from 10min to 15min

---

vars/common.yml
vars/preview.yml
vars/production.yml
vars/staging.yml

Rather than defining maintenance mode in the common vars, which will
make it affect all environments simultaneously, we should define it on a
per-environment basis so that we are able to toggle it for specific
environments without the risk of accidentally also turning it on for
production.
This will allow us to more safely have a job that can toggle maintenance
mode on/off.

Move maintenance mode variable

---

vars/production.yml

Applications for a framework are our busiest period. Suppliers
submitting declarations and services puts a high load on the
supplier-frontend and the api. We have load tested to ensure that with
this level of instance counts we can handle approximately 2.5X the
expected traffic.

Increase api and supplier instance counts for g10 applications

---

vars/staging.yml

See this PR for context: https://github.com/alphagov/digitalmarketplace-aws/pull/376
We increase the instance counts on staging to match prod. This was for
load testing in the run up to opening G-10 applications. The load
testing is complete so we can reduce the counts back to their original
levels.

Reduce staging instance counts

---

default.nix

* terraform state DB was already upgraded by s/one that got a new version with brew

Upgrade terraform to 0.11.7

---

vars/production.yml

Bump the number of API and Supplier-FE instances to 20 each, and give
the Supplier-FE 1GB of memory each for the remaining application period.
https://trello.com/c/VJ9MdlsQ/310

Scale up+out for supplier applications

---

vars/production.yml

We hit our PaaS quotas when trying to scale to 20 instances, so we'll
stick to 15 and reduce the supplier-fe quota slightly.
https://trello.com/c/VJ9MdlsQ/310

Scale to 15 instances

---

vars/production.yml

We have a larger quota now, so we can scale the api and the
supplier-frontend a bit more generously to give us a greater level of
confidence in handling the anticipated final spike in traffic.

Scale for last day of applications

---

vars/production.yml

After G-Cloud 10 applications have closed, we can scale the platform
back to normal levels.
For tomorrow.

Scale back to normal levels

---

terraform/modules/jenkins/iam.tf

We'd like Jenkins to run the virus scanning job for uploaded files. The
Jenkins role needs the correct permissions to do this.
The other part of this adding permissions on the bucket to allow Jenkins
to list it. We don't currently manage those buckets via Terraform so
this has been done through the GUI via the S3 Access Control List.

Give Jenkins role permissions for prod submissions bucket

---

scripts/clean-db-dump.sql

When running functional tests against our test environments, we have a
wrapper around our call to Notify that translates certain email domains
to other domains which will generate successful test responses from
Notify. `@gov.uk` is not one of these and feels too generic to blacklist
in case we actually block legitimate emails out. `@example.gov.uk` feels
safer, so let's use this when cleaning up the data.
The sandbox email addresses are defined in the `config.py` of each frontend app.
At the moment we have a load of emails stuck in Notify's queue from our tests that they keep trying to deliver. We're bad people if we keep asking them to send emails to addresses that we know are not real.

Use sandbox emails when cleaning dump

---

terraform/modules/jenkins/iam.tf

See these supporting PR:
https://github.com/alphagov/digitalmarketplace-credentials/pull/119
https://github.com/alphagov/digitalmarketplace-jenkins/pull/90
https://github.com/alphagov/digitalmarketplace-scripts/pull/233
We have a job on Jenkins that runs daily that uploads a csv of DOS
opportunity details to the preview and production communications
buckets.
Currently, the script that does this is having AWS credentials injected
into it as env variables. These creds are coming from the jenkins users
aws config file. That config file is a template populated by Ansible,
which gets the creds from the jenkins vars file in the credentials
repo.
The AWS creds in the credentials repo are for an AWS user we have set up
called `deploy`. This user is a hangover from when we used to use …

Give Jenkins role permissions on s3 buckets

---

vars/production.yml

For [this trello ticket.](https://trello.com/c/gdIMHCCq)
This increases the supplier frontend and api instance counts to match
what we were running for G-Cloud 10 applications.
We currently have a 200GB memory limit on PaaS of which we're currently
using about 26GB (across all spaces). This bump will add at most an extra 64GB of memory use
(if we were to release both applications at the same time), so we should
still be well within limits.

Scale supplier and api for DOS3 applications

---

dmaws/hosted_graphite/create_dashboards.py
grafana/dm-overview.json
scripts/create-hosted-graphite-dashboards.py

docopt needs to be imported from docopt, otherwise you get a `module not
callable` error.
The path to the json files also needed an extra `..`
Adds a new panel to the overview dashboard which aggregates the values of
the retry metric for all the apps and displays it.
This is already applied, if you look at the monitor you should see how it looks.

Add retries to grafana overview dashboard

---

dmaws/hosted_graphite/create_alerts.py

By only alerting every 60 minutes we would miss some 500s if they
occurred within an hour or the original alert.
By changing to `state_change` we should see alerts for all 500s.
This is already actually the setup we're using. I changed it through the hosted graphite GUI without realising it should also be updated here.

Notify for 500's on state_change

---

requirements.txt

aws-auth, the tool we use for temporary credentials, has been updated to
work only with the new file name format generated by aws cli for
temporary credentials. This changed in version 1.14
This version works.

Bump aws cli to 1.15.67

---

terraform/accounts/main/main.tf
terraform/accounts/main/route53.tf
terraform/modules/jenkins/ec2.tf
terraform/modules/jenkins/outputs.tf
terraform/modules/jenkins/security_group.tf
terraform/modules/jenkins/variables.tf

Change jenkins2 to jenkins3. This is due to running into the letsencrypt rate limit for certificates of 20 per week. Using a different subdomain allowed me to continue developing. After new Jenkins is out we can point the original domain at the new box so it shoudn't be too much of an issue.
This also adds a security group file to the Jenkins module - this is mostly just a straight copy of the jenkins security account defined in the main account (which we can drop after the move). The main difference is the programatic inclusion of the jenkins elastic ip address in the inbound https rule. This just means we don't need to update the terraform credentials file with the new ip address.
The new ec2 instance definition programatically pulls in the new security group rather than hard coding the …

Jenkins2 becomes Jenkins3. And some tweaks.

---

terraform/accounts/main/route53.tf
terraform/modules/jenkins/ec2.tf
terraform/modules/jenkins/elb.tf
terraform/modules/jenkins/outputs.tf
terraform/modules/jenkins/security_group.tf

This was done to get a free certificate, rather than having to get one
from letsencrypt. The main motivation was I kept bumping in to the
letsencrypt rate limit on issuing certificates of 20 per week.
This code sets up an CNAME record for ci3.market.... which points to the
DNS name of the elb. The elb terminates our tls and proxies the request
on to the Jenkins instance via http. This is all within our VPC and
subnet.
The ELB also passes tcp connections through port 22 to allow ssh access.
There are two security groups - one for the ELB with all our usual
whitelisted IP address as the only allowed ingress, and one for the
instance itself, which only allowed ingress from the ELB.

Put Jenkins3 behind ELB

---

scripts/import-and-clean-db-dump.sh

https://trello.com/c/0vtBEhdx/55-make-db-restore-job-run-in-transaction
This flag creates a transaction for the session 
https://stackoverflow.com/a/38378603/3967444
https://stackoverflow.com/questions/1651219/how-to-check-for-pending-operations-in-a-postgresql-transaction/28802471#28802471
Tested with:
```
(venv) benvandersteen@gds5077:~/gds/branches/digitalmarketplace/digitalmarketplace-jenkins$ echo "select txid_current(); begin; select txid_current(); commit;" | psql --single-transaction -d digitalmarketplace
txid_current 
--------------
1384807
(1 row)
WARNING:  there is already a transaction in progress
BEGIN
txid_current 
--------------
1384807
(1 row)
COMMIT
WARNING:  there is no transaction in progress
(venv) benvandersteen@gds5077:~/gds/branches/digitalmarketplace/digitalmarketpl …
```

Add '--single-transaction' flag to db restore

---

paas/brief-responses-frontend.j2

alphagov/digitalmarketplace-brief-responses-frontend#75 changed the service provider for emails from the brief-responses-frontend app.
This commit changes the template for the app so that the Notify API key is in its environment when it is started.
Once this change has been merged the app will need to be rebuilt on preview so that it can pick up the Notify key. This will then the functional tests should pass on preview.
The manifest at the top of this PR includes both the Mandrill and Notify API keys; when migration has been completed the commit e9526ee55237d0990df68e9be98c00f0c841ac7c can be reverted.
This is to finish off [this][ticket] tech debt ticket.
[ticket]: https://trello.com/c/jESNKsXH

brief-responses-frontend: Remove Mandrill and use Notify

---

scripts/import-and-clean-db-dump.sh

Last change for the `import-and-clean-db-dump` script had the order of arguments slightly wrong, so the script failed with
```
psql: invalid connection option "bcrypt_password"
```
This commit should fix it 🤞

Fix "Add '--single-transaction' flag to db restore"

---

requirements.txt

Snyk was showing a low severity vulnerability for boto3, fixable by
bumping to this verison. See here: https://app.snyk.io/vuln/SNYK-PYTHON-BOTO3-40617

Bump boto3 to version 1.4.5 to satisfy snyk

---

vars/production.yml

This reverts commit 35c1b56e3242ec6b563ea04c0e10e301b9753499.
DOS3 applications are now closed so we can return to the default
instance count and memory size of the api and supplier fe.

Revert "Scale supplier and api for DOS3 applications"

---

aws-auth.nix

this should isolate aws-auth's python env from the enclosing session's python env, particularly a problem when one is py2 and the other py3.

nix: strip PYTHONPATH from env when wrapping aws-auth

---

scripts/generate-s3-post-url-data.py
terraform/accounts/backups/access.tf
terraform/accounts/backups/main.tf
terraform/accounts/backups/s3_buckets.tf

#### Setting up cross region replication of incoming backups.
Predominantly followed this example, changing names to be in line with existing convention:
https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#using-replication-configuration
Only new incoming backups will be replicated (as per https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-what-is-isnot-replicated.html) and the backups will be kept for 7 days (see https://github.com/alphagov/digitalmarketplace-aws/pull/429/files#diff-fe12ef74960acd2feb5dc4ef2c4d6a66R75); this has been cleared with the dev team and @louzoid-gds .
In order to give the new region bucket similar permissions to the regular backups bucket I removed the hard coded json bucket policy and created 2 policy documents. One inheriting from the other. …

98-set-up-cross-region-replication-for-our-backups-s3-buckets

---

scripts/generate-s3-post-url-data.py
terraform/accounts/backups/s3_buckets.tf

According to
https://github.com/terraform-providers/terraform-provider-aws/issues/665
Unless you give your replication rule an id it will replan the 'changes' on every plan run.
https://trello.com/c/KqUhQHFv/126-stop-terraform-replannig-replication-config

Stop terraform replanning replication config

---

Makefile
README.md
default.nix

Python36 includes the venv module which means we no longer need virtualenv to be installed on the development system

Remove requirement on virtualenv

---

terraform/environments/preview/main.tf
terraform/environments/preview/variables.tf
terraform/environments/production/main.tf
terraform/environments/production/variables.tf
terraform/environments/staging/main.tf
terraform/environments/staging/variables.tf
terraform/modules/antivirus-sns/iam.tf
terraform/modules/antivirus-sns/main.tf
terraform/modules/antivirus-sns/s3-notifications.tf
terraform/modules/antivirus-sns/subscriptions.tf
terraform/modules/antivirus-sns/variables.tf

For [this trello ticket](https://trello.com/c/DwwT9fw5).
The module sets up an SNS topic for sending notifications to the
antivirus app.
We need to set up notifications for the S3 buckets we want to monitor
for file uploads. These notifications will publish a message to the file
upload topic whenever a file is created in any of them. That published
message is then distributed to all subscriptions. That's next.
This adds a subscription to the file upload topic for an endpoint on the
antivirus api. The api will be using basic auth which is included in the
endpoint described here. The creds are in the creds repo.
The endpoint _has_ to be able to autoconfirm the subscription request
that is sent to it or this code will not apply.

Antivirus SNS notifications

---

paas/antivirus-api.j2
terraform/README.md
terraform/modules/antivirus-sns/iam.tf
terraform/modules/application-logs/variables.tf
vars/common.yml

https://trello.com/c/i30jDD69/14-automatically-virus-scan-uploaded-files
Here we do a couple of things:
- namespace the `sns_feedback` IAM policy with the environment name to allow staging & production's policies to co-exist.
- add `antivirus-api` to terraform's list of apps to create log groups for

terraform: further refinement of antivirus-api infrastructure

---

grafana/dm-apps.json

Trello https://trello.com/c/i30jDD69/14-automatically-virus-scan-uploaded-files
This makes our dashboards aware of the av-api. Has been pushed and appears to work.

grafana: add antivirus-api to apps

---

vars/production.yml

Seems like the most sensible thing, for a low-demand service.

antivirus-api: specify 2 instances on production

---

vars/common.yml

Seems to be what `clamd` needs.

paas: antivirus-api: give these instances 2G of memory on all stages

---

paas/router.j2

A prerequisite for https://github.com/alphagov/digitalmarketplace-router/pull/28

router paas env vars: set `DM_ANTIVIRUS_API_URL`

---

paas/admin-frontend.j2
paas/router.j2
terraform/accounts/main/jenkins_instance_profile.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/preview/variables.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/production/variables.tf
terraform/environments/staging/s3_buckets.tf
terraform/environments/staging/variables.tf

Trello: https://trello.com/c/FtV7sVMU/138-admin-download-all-suppliers-for-framework-endpoint-locks-up-an-api-process
Three shiny new buckets:
`digitalmarketplace-reports-preview-preview`
`digitalmarketplace-reports-staging-staging`
`digitalmarketplace-reports-production-production`
Copies permissions/policy from the Agreements buckets (which has no explicit policy for the staging bucket).

Create S3 buckets for admin reports

---

terraform/environments/preview/variables.tf
terraform/environments/production/variables.tf
terraform/environments/staging/variables.tf

## Remove unused variables
It would appear that these have been at least partially copied from account/main/vairiables.tf?
We don't need that many variables injected in to these terraform modules so this commit strips un-needed variables
to reduce confusion and prevent extraneous code.
https://trello.com/c/vSknqk9R/148-remove-extraneous-variables-in-environments-variablestf-files

148-remove-extraneous-variables-in-environments-variablestf-files

---

terraform/modules/iam-common/admin.tf

## Remove arn:aws:iam::${var.aws_dev_account_id}:role/s3-only references from terraform
This _role_ is not created anywhere. A group is. A role is not.
We have references to an s3-only role for the dev account. This isn't created anywhere and doesn't exist.
arn:aws:iam::${var.aws_dev_account_id}:role/s3-only
https://trello.com/c/PvVlMCTz/568-remove-arnawsiamvarawsdevaccountidrole-s3-only-references-from-terraform-this-role-is-not-created-anywhere
https://console.aws.amazon.com/iam/home?region=eu-west-1#/roles

568-remove-arnawsiamvarawsdevaccountidrole-s3-only-references-from-terraform-this-role-is-not-created-anywhere

---

terraform/accounts/main/jenkins_instance_profile.tf
terraform/environments/preview/s3_buckets.tf

Trello: https://trello.com/c/FtV7sVMU/138-admin-download-all-suppliers-for-framework-endpoint-locks-up-an-api-process
Enables the Jenkins role to access the preview and staging buckets, so we can test the script (and maybe even run functional tests in future).
I've already run terraform plan/apply for this so the changes reflect reality.

Jenkins IAM user can read/write preview/staging report buckets

---

terraform/environments/preview/main.tf
terraform/modules/antivirus-sns/logs.tf
terraform/modules/antivirus-sns/variables.tf
terraform/modules/log-streaming/outputs.tf
terraform/modules/log-streaming/src/main.js

For [this trello ticket](https://trello.com/c/CXxL1M8x).
SNS creates logs in CloudWatch to give us feedback on the sucess or
failure of its notifications. This is useful stuff and we should make it
more accessible by streaming it out to Kibana.

Stream antivirus sns feedback to Kibana

---

terraform/modules/antivirus-sns/main.tf

This setup will retry once immediately, then 5 more times with a linear
backoff with the first retry after 1 second and the last after just
under an hour.

Extend sns topic delivery retries to an hour

---

terraform/modules/antivirus-sns/main.tf

This is the max value that can be used with 5 retries that will apply.
Any higher and AWS will claim that the total retry period is over an
hour. I do not fully understand how it calculates this. This came from
trial and error.

Set maxDelayTarget slightly lower

---

default.nix

This requirement had been hidden by pip caching my wheels.

default.nix: add libffi dependency

---

paas/antivirus-api.j2

Didn't check its output again after I neatened it up with the whitespace-stripping.

antivirus-api paas manifest template: solve lack of indentation for DM_DEVELOPER_VIRUS_ALERT_EMAIL

---

terraform/environments/staging/s3_buckets.tf

Trello: https://trello.com/c/FtV7sVMU/138-admin-download-all-suppliers-for-framework-endpoint-locks-up-an-api-process
The new CSV report creation and download is working great on Preview. 
To test on staging, we need Jenkins to have write access on the S3 reports bucket in order for the script to run successfully. Then we can release the Router and Admin FE to staging, and test the download.
(Planned and applied on staging)

Give Jenkins access to reports S3 bucket on Staging

---

scripts/clean-db-dump.sql

Create fake brief responses for DOS3 and remove references to `nameOfOrganisation` and `organisationSize` from 'make fake declaration' SQL
These fields have been migrated on to the supplier object.
https://trello.com/c/C3oFh4yz/477-update-sql-to-create-fake-brief-responses-for-dos3-on-preview-and-staging

477-update-sql-to-create-fake-brief-responses-for-dos3-on-preview-and-staging

---

dmaws/utils.py
requirements.txt
tests/test_utils.py

Trello: https://trello.com/c/XuJNrSHX/483-vulnerability-fix-weekly-tracking
- Upgrades `requests` to 2.20.0 following Snyk vulnerability warning
- Removes `six` (Py2 support no longer required in this repo)
- Removes unused utils functions `dict_from_path`, `safe_path_join` and `param_to_env ` (I did a full grep and some digging in the history but can't find any usage).

Update requests library

---

terraform/environments/preview/main.tf
terraform/environments/production/main.tf
terraform/environments/staging/main.tf
terraform/modules/antivirus-sns/main.tf
terraform/modules/antivirus-sns/outputs.tf
terraform/modules/antivirus-sns/variables.tf
terraform/modules/log-metrics/main.tf
terraform/modules/log-metrics/variables.tf

https://trello.com/c/cQEkAi5b/214-enable-hosted-graphite-alerts-for-final-failed-sns-deliveries
Triggered by both "final retry" "failure"s and 4xx responses from the "success" log group.
This includes quite a bit of variable wiring around the place so we can pull e.g. the max number of retries to filter for and the names of the log groups from the various places they're decided.

terraform: add "*-dropped-antivirus-sns" log metrics, sourced from both failure and success sns feedback logs

---

dmaws/hosted_graphite/create_alerts.py

https://trello.com/c/cQEkAi5b/214-enable-hosted-graphite-alerts-for-final-failed-sns-deliveries
It even works.

hosted graphite alerts: add "Production antivirus 'dropped' SNS messages" alert

---

example_manifests/api-manifest.yml.example
example_manifests/buyer-frontend-manifest.yml.example
example_manifests/router-manifest.yml.example
example_manifests/search-api-manifest.yml.example

Trello: https://trello.com/c/GNMyCgSJ/232-example-paas-manifest-yaml-files
Generated some example PaaS manifests for Preview (with all credentials etc stripped) for:
- API
- Search API
- Router
- Buyer FE (the other frontend apps are similar enough that I only did this one - happy to add more if people think there's value in it)
These manifests are unlikely to change drastically in the future, but if they do, I've included a line at the top of the examples on how to generate new ones.
I've left in values for routes and URLs as these are public (described in the `vars` folder of this repo). Please double check that I've taken everything else out!

Example PaaS manifests for API, Search API, Buyer FE and Router

---

terraform/modules/iam-users/infrastructure.tf
terraform/modules/jenkins/elb.tf
terraform/modules/jenkins/s3_bucket.tf

We want to be able to audit who is accessing our Jenkins build server, and when.
This PR enables access logging on the Elastic Load Balancer that sits in front of our Jenkins box; this means that all SSH and HTTPS access will be logged.
The logs are stored hourly in an S3 bucket, in a compressed format.
For more details on how this works, see the [Trello ticket][ticket].
The Terraform for these changes have already been tested and applied, and the logging is now taking place.
[ticket]: https://trello.com/c/S7iFoAU8/253-configure-jenkins-box-ssh-access-logging

Enable access logging on Jenkins load balancers

---

default.nix

So we're not left scratching our heads when the tests won't run.

default.nix: set forDev to true by default

---

terraform/accounts/main/jenkins_instance_profile.tf

We want our Jenkins server to be able to upload logs to CloudWatch.
Part of https://trello.com/c/Uf14tLzG/247-jenkins-get-the-job-logs-out.

Add CloudWatch Logs policy to Jenkins instance profile

---

Makefile

https://trello.com/c/6vpsFZVM/552-search-api-releases-can-still-cause-a-flood-of-500s-as-instances-lose-contact-with-es
This is to ensure the new app's assigned service credentials have taken effect. Again, particularly a problem with new aiven-backed services, though this is apparently something that's being worked on and we should be able to remove this stopgap at some point.
Seems to work when performed from a local machine.

make deploy-app: add "wait" after pushing app before starting it

---

vars/production.yml

Doh.
https://trello.com/c/GELoPi7h/565-reduce-number-of-av-api-instances-on-production

antivirus-api: *actually* set instances to 2 by spelling the app correctly

---

paas/brief-responses-frontend.j2

* This endpoint is now defined with the blueprint prefix in the brief-responses-frontend

Use metrics as blueprint

---

vars/common.yml

* Add explicitly defined route (/metrics) for metrics
* This route allows us to bind the whitelisting route service
* Bind digitalmarketplace_prometheus service using the app manifest

Deployment requirements for metrics

---

paas/brief-responses-frontend.j2

@philandstuff has found a work around for us to have _metrics! 🙌 
This env var controls where the `gds_python_metrics` puts our metrics endpoint and can be merged once his PR is deployed 
https://trello.com/c/6DZK1NzZ/349-update-metrics-path-with-now-re-have-a-workaround

Update metrics path with _ now RE have a workaround

---

default.nix

default.nix: ensure venv is created relative to default.nix, not cwd

---

scripts/clean-db-dump.sql

https://trello.com/c/JgsizEmz
While I don't _think_ the exact fields being used here _should_ cause us to be at risk, all it takes is for someone less experienced to need to include an extra field's data, and decide to simply copy & paste an existing line and include a text-based field - at this point we would open ourselves to the string being able to escape from the confines of its intended json key using the `"` character.
I've run this against an _already cleaned_ version of the database on my local machine, because that's all I think I'm able to do. It appears to do the right thing. Anyone got any bright ideas as to how to safely test this against the real target short of merging it & trying it for reals?

clean-db-dump.sql: perform construction of mock json in a safer way than pure string formatting

---

paas/router.j2
vars/preview.yml
vars/production.yml
vars/staging.yml

To help ease our load testing (see Trello: https://trello.com/c/tFiYL9vk/379-load-test-the-supplier-account-creation-journey), it'd be nice to switch rate limiting on and off per environment.
This PR sets a `DM_RATE_LIMITING_ENABLED` variable in the router's PaaS environment vars, that the router can then use to include the rate limit config (or not). 
This is part 1 of 2 - set the vars to `true` for each environment by default.
Part 2 (router) incoming.
Tested this locally with `make generate-manifest APPLICATION_NAME=router STAGE=preview`. Setting to `false` means the var is not generated.

Add rate_limiting_enabled flag to router PaaS manifest

---

vars/preview.yml

Trello: https://trello.com/c/tFiYL9vk/379-load-test-the-supplier-account-creation-journey
Doing this manually isn't working so let's go through the 'official channels'.
The changes are only for preview, so shouldn't affect other envs if we 'temporarily' forget about this.

Temporarily turn off preview rate limit and bump router instances to 3

---

paas/router.j2
vars/preview.yml
vars/production.yml
vars/staging.yml

The Nginx Jinja isn't happy with falsy/missing environment values.
Staging and Prod are enabled, Preview is disabled for the moment.

Always set DM_RATE_LIMIT_ENABLED var to a value

---

vars/preview.yml

Load testing (https://trello.com/c/tFiYL9vk/379-load-test-the-supplier-account-creation-journey) is now done.
Re-enable rate limiting on preview, and scale back down to 2 router apps.

Re-enable rate limiting on Preview

---

terraform/environments/preview/alarms.tf
terraform/environments/production/alarms.tf
terraform/modules/logging/alarms/email-notification/outputs.tf
terraform/modules/logging/alarms/email-notification/sns.tf
terraform/modules/logging/alarms/email-notification/variables.tf
terraform/modules/logging/alarms/missing-logs/alarms.tf
terraform/modules/logging/alarms/missing-logs/variables.tf
terraform/modules/logging/alarms/slow-requests/alarms.tf
terraform/modules/logging/alarms/slow-requests/variables.tf
terraform/modules/logging/alarms/status-code/alarms.tf
terraform/modules/logging/alarms/status-code/variables.tf

When an AWS alarm triggers a notification it's actually triggering a 'topic'.
A topic is just a list of emails that will all get the same notification.
In our case we want one email address to receive bad :( notifications and one email address to receive good :) email notifications.
To do this we have to create 2 'topics', a 'good' topic and a 'bad' topic, each with one email registered to it. 
When a good notification is triggered it is sent to the 1 slack integration email subscribed to that 'topic'.
And the 1 slack integration email subscribed to our bad 'topic' gets the bad notifications.
This allows us to show them as green and red in Slack because you can only show icons for different users or emails, not based on the content of the message.
In this PR we create the new 'good' …

Add recovery emails for alarms in terraform

---

terraform/accounts/main/alarms.tf
terraform/accounts/main/jenkins_instance_profile.tf

* Add permissions for jenkins instance to PutMetricData in to Cloudwatch (used with cloudwatch-logs-agent)
* Add new alarms for disk space on jenkins
https://trello.com/c/PdXsLT6d/377-aws-alarm-for-disk-space-on-jenkins

377-aws-alarm-for-disk-space-on-jenkins

---

Makefile
requirements.txt
scripts/add-application-network-policies.sh
vars/preview.yml

This does a few things, but luckily should only have an effect on preview for now:
- adds secondary `.apps.internal` routes to each of the preview api apps
- adds a new step in the `make deploy-app` process which will attempt to create the network policies the newly created app is going to need. Do read the extensive comments on this, because it's quite carefully considered (!) and should hopefully work even in the face of simultaneous release procedures of both parties of an ingress/egress relationship.
- these ingress/egress relationships are defined in the vars yaml on the "egress" side of the relationship by defining a `egress_to_applications` key. These should automatically get picked up as ingresses for the _referred_ app using a little bit of `yq` …

deploy-app: add network policy handling, enable for preview

---

terraform/accounts/development/s3_buckets.tf
terraform/accounts/main/jenkins_instance_profile.tf
terraform/modules/iam-users/admins.tf
terraform/modules/iam-users/developers.tf

As part of:
https://trello.com/c/uUxYtjSt/345-gdrive-client-alternatives-consolidate-data-dumps-store-in-s3
We need a new bucket that devs can access to for jenkins to put the db dumps in.
https://trello.com/c/0jAgMP0d/405-gdrive-client-alternatives-db-dumps-to-s3-not-drive

Create new bucket to store dev cleaned db dumps and give access

---

paas/admin-frontend.j2
paas/api.j2
paas/brief-responses-frontend.j2
paas/briefs-frontend.j2
paas/buyer-frontend.j2
paas/router.j2
paas/supplier-frontend.j2
paas/user-frontend.j2

I apologize for the temporary ugliness of this solution, but it really is meant to be temporary as I switch the environments over to using internal urls one by one.

app environment variables: use ugly "if" statement to switch these to the .apps.internal addresses for preview only

---

scripts/apply-cleaned-db-to-target.sh

As part of 
https://trello.com/c/0jAgMP0d/405-gdrive-client-alternatives-data-dumps-only
We need to update the acl on the uploaded dumps, they're going in but we can't get them out without handing over management of the acl to the bucket owner (and therefore terraform)

Change acl to bucket-owner-full-control on uploaded dev db dumps

---

paas/admin-frontend.j2
paas/api.j2
paas/brief-responses-frontend.j2
paas/briefs-frontend.j2
paas/buyer-frontend.j2
paas/router.j2
paas/supplier-frontend.j2
paas/user-frontend.j2

Reverts alphagov/digitalmarketplace-aws#513
As long as this is merged, preview will always need its router restarted every time an API is released.

Revert "[TAKE 2] app environment variables: use ugly "if" statement to switch these to  the .apps.internal addresses for preview only"

---

vars/preview.yml

I guess this is the next logical step...

preview: remove .cloudapps.digital routes from apis

---

scripts/apply-cleaned-db-to-target.sh
terraform/accounts/development/s3_buckets.tf

[Ticket](https://trello.com/c/FDv4IfBt/417-clean-prod-db-dump-and-apply-deletes-the-old-dev-dump-and-creates-the-new-dump-we-could-just-use-versions-for-this)
Using the version capabilities of S3 buckets we can have old versions of the database dump, just in case we need them. At the moment we just delete them.

Add versioning to cleaned_db_dumps bucket

---

vars/preview.yml

https://trello.com/c/QOj2iMLO
Even though we're likely to yank this all from preview soon, it would be nice to have committed the proper solution for this so it's clear what needs to be restored to bring private apps back...

preview private routes: open a public .cloudapps.digital route for /_metrics only

---

terraform/environments/preview/alarms.tf
terraform/environments/production/alarms.tf
terraform/modules/logging/alarms/README.md
terraform/modules/logging/alarms/dropped-av-sns/alarms.tf
terraform/modules/logging/alarms/dropped-av-sns/variables.tf
terraform/modules/logging/alarms/missing-logs/alarms.tf
terraform/modules/logging/alarms/slow-requests/alarms.tf
terraform/modules/logging/alarms/status-code/alarms.tf
terraform/modules/logging/log-metric-filters/main.tf

https://trello.com/c/gHYwVkSu/413-re-create-an-alarm-for-dropped-av-sns
* Update comment with more info
* Update comment with correct second value
* Update readme with alarm_recovery_email_topic_arn arg for log examples
* Add new dropped-av-sns alarm module for creating dropped av alarm
* Add readme entry for new dropped av sns alarm
* Apply new dropped av sns alarm to preview
* Apply new dropped av sns alarm to production

413-re-create-an-alarm-for-dropped-av-sns

---

terraform/modules/log-streaming/lambda.tf

As per email from AWS: 6.10 node.js is EOL
8.10 is newest available Lambda runtime
8.10 is supported until 12/2019
See:
| Release  | Status              | Codename    |Initial Release | Active LTS Start | Maintenance LTS Start | End-of-life               |
| :--:     | :---:               | :---:       | :---:          | :---:            | :---:                 | :---:                     |
| [6.x][]  | **Maintenance LTS** | [Boron][]   | 2016-04-26     | 2016-10-18       | 2018-04-30            | 2019-04-30                |
| [8.x][]  | **Maintenance LTS** | [Carbon][]  | 2017-05-30     | 2017-10-31       | 2019-01-01            | December 2019<sup>1</sup> |
| [10.x][] | **Active LTS**      | [Dubnium][] | 2018-04-24     | 2018-10-30       | April 2020            | April 2021 …

658-aws-lambdas-are-using-old-version-of-node

---

vars/preview.yml

Trello: https://trello.com/c/LcuyPXvI/664-app-release-failing-healthchecks
The Search API was failing to start up on preview as the healthchecks were failing.
The healthcheck endpoint is generated from the first item in the `routes` var:
`health-check-http-endpoint: {{ routes[0].partition('/')[1:]|join("") }}/_status?ignore-dependencies`
Moving the metrics down below it should do the trick.

Don't use metric routes for healthchecks

---

terraform/accounts/production/main.tf

So it is consistent with all the environments
Main/Backups/Development all are using v1
There will be breaking changes on csw master soon
Co-authored-by: Alex <alex.kinnane@digital.cabinet-office.gov.uk>
Co-authored-by: Dan <dan.jones@digital.cabinet-office.gov.uk>
Co-authored-by: Toby <toby.lornewelch-richards@digital.cabinet-office.gov.uk>

Pin the CSW git reference in production

---

paas/_base.j2
paas/brief-responses-frontend.j2
vars/common.yml
vars/preview.yml

https://trello.com/c/wGJZQFxO/427-put-metrics-on-api
* Move _metrics PaaS env arguments from brief-responses only to global base so they are available for every deployment
* Move metrics routes definitions from preview vars to common vars so these routes are defined on next release of all stages

427-put-metrics-on-api

---

vars/common.yml

https://trello.com/c/8tJsE7Gp/

paas: bump memory for buyer and supplier frontends to 700M

---

terraform/modules/iam-users/users/main.tf

Trello: https://trello.com/c/oC3a9na4/699-set-up-ares-on-everything
The IAM user has already been created for Ares so that should be a no-op; this will force-destroy Jonathan's IAM user (we've already removed his group membership and permissions).

Remove Jonathan, add Ares from IAM users

---

example_manifests/api-manifest.yml.example
example_manifests/buyer-frontend-manifest.yml.example
example_manifests/router-manifest.yml.example
example_manifests/search-api-manifest.yml.example
paas/_base.j2

https://trello.com/c/EGGLjxJQ/456-remove-instances-of-dmmetricsnamespace
This environment variable is no longer required, we've gotten rid of `dmutils/metrics.py` which used it.
https://github.com/alphagov/digitalmarketplace-utils/pull/504

Remove old, unused, dmutils/metrics.py environment variable

---

Makefile
scripts/map-route.sh

Our deploy-app recipe will create a `-release` app with a route and only removes the route after it has been started. If the app start fails this means there can be a route pointing to a dead app. See https://trello.com/c/x76uyB81/692-a-failed-api-release-will-leave-a-dangling-route for info on how this came up.
This commit changes the deploy-app recipe so that the release app will be created without a route, and then if the app fails to start nothing else will be broken 🤞. The route mapping is done by a new script, `scripts/map-route.sh`, that gets the desired route(s) from the app manifest.
This should also have the bonus effect of meaning our release process causes less downtime in our metrics.
This has been tested on preview.

Change deploy-app to push new app without route

---

vars/production.yml

Our supplier-frontend has been experiencing a lot of traffic recently;
we've bumped the memory, let's bump the number of instances as well.
Hopefully this will ease up the issues we've been seeing https://trello.com/c/nFfzjblY/697-memory-on-supplier-buyer-router-api

Increase number of instances for supplier-frontend

---

terraform/modules/logging/alarms/missing-logs/alarms.tf
terraform/modules/logging/alarms/slow-requests/alarms.tf

https://trello.com/c/0OgvW0sn/750-search-api-missing-logs-alarm-did-not-raise-for-30-minutes-when-search-api-app-was-down
* Move missing logs to 5 minutes to cause to trigger at 12ish mins
* Do not trigger slow request on missing logs, missing-logs alarms handle this

750 search api missing logs alarm did not raise for 30 minutes when search api app was down

---

default.nix

This actually ends up being an identical package to the default from nixpkgs `19.03`, which is fun. But keeping the override in because I predict having to bump it soon.

default.nix: bump terraform to 0.11.13 

---

vars/production.yml

Trello: https://trello.com/c/gUe0oyAQ/3-scale-up-production-apps-ready-for-g11-application-deadline
We're anticipating high traffic in the last week of applications.
Bumps API and Supplier FE to 10 instances each.
Next week we will go a bit higher if necessary (last year we maxed at 20x API and 15x Supplier https://github.com/alphagov/digitalmarketplace-aws/commit/c9de45c81af7879dfae88a8956c81c3d37ecbdf1#diff-5318b18620ce14c1fca80d3b8f684840)

Scale API and supplier FE for G11 applications

---

db-backup/create-db-dump.sh
vars/common.yml

Trello: https://trello.com/c/f1PbVXEW/785-db-backup-app-runs-out-of-memory
Our `db-backup` app is created with 128MB of memory, even though our maximum memory usage for the task is later set to 2G:
`cf run-task db-backup "/app/create-db-dump.sh" --name db-backup -m 2G -k 2G`
Also adds a commit to hide the DB service credentials from Jenkins console output (please check I've got my bash the right way round here...)

Increase DB backup app memory

---

Makefile
vars/common.yml

Trello: https://trello.com/c/f1PbVXEW/785-db-backup-app-runs-out-of-memory
Ben spotted that the task has different quotas (as it's run in a separate container): https://github.com/alphagov/digitalmarketplace-aws/pull/404/files
Bumping the quotas there to 3G each seems to work (i.e. the task failed with a different error, not 'out of memory' 😸).
Therefore we don't need to have the app memory at 2G - I've put it back down to 128M.

Increase memory and disk quotas for backup task 

---

Makefile

Trello: https://trello.com/c/f1PbVXEW/785-db-backup-app-runs-out-of-memory
Discovered during the DB backup failures.
Previously the task was setting its own value for DUMP_FILE_NAME - 1 second later, according to the timestamp - which was conflicting with the Jenkins DUMP_FILE_NAME, and causing the decryption check step to fail.
See Jenkins job update: https://github.com/alphagov/digitalmarketplace-jenkins/pull/219

Provide DUMP_FILE_NAME as parameter to deploy-db-backup-app task

---

vars/common.yml

* Add _metrics routes and prom-service to:
* buyer
* briefs
* user
* admin
https://trello.com/c/Fqq8RCEb/495-add-metrics-to-briefs-user-and-admin-frontends

Add _metrics routes and prom-service for buyer, briefs, user and admin

---

Makefile
scripts/add-ip-whitelist-route-service.sh
vars/ip_whitelist_routes.json

* Add new variable file for script to use.
* These cannot be part of the manifest bacuse the manifest template variables are filled in inside generate-manifest which will also strip any custom variables out
* Add script which takes uses variables file to add routes to ip-whitelisting-service
* Run script in deployment after routes are created
https://trello.com/c/Ktinf9rQ/457-script-to-add-ip-whitelisted-routes-on-deploy

Add new add-ip-whitelist-route-service.sh script

---

Makefile
scripts/add-application-network-policies.sh
vars/preview.yml

Remove internal route setup from deployment
Keep script with readme for when we decide to use them
* Rm script call in `deploy-app`
* Add TODO explaining when to reimplement
* Rm internal route definitions from `preview.yml` and fall back to `common.yml`
* Rm `egress_to_applications` values from `preview.yml`
https://trello.com/c/IMVZsuoJ/502-rm-internal-routes-from-preview-for-now

502-rm-internal-routes-from-preview-for-now

---

vars/common.yml

Scaling up Supplier FE to 1G memory on all environments (so we can check the deployment).

Increase Supplier FE memory to 1G

---

vars/common.yml
vars/production.yml

Both number of instances and memory

paas instances: scale down production instances following G11's close

---

vars/production.yml

api & supplier-frontend 10 -> 7?
Want to do this before the weekend.

production instances: scale down even more following g-cloud-11's closing

---

terraform/accounts/backups/cloudwatch.tf
terraform/accounts/development/cloudwatch.tf
terraform/accounts/main/cloudwatch.tf
terraform/accounts/production/cloudwatch.tf
terraform/modules/cloudtrail/README.md
terraform/modules/cloudtrail/main.tf
terraform/modules/cloudtrail/modules/cloudtrail-bucket/outputs.tf
terraform/modules/cloudtrail/modules/cloudtrail-validate-logs-role/main.tf
terraform/modules/cloudtrail/modules/cloudtrail-validate-logs-role/variables.tf
terraform/modules/cloudtrail/variables.tf

We want to be able to validate our CloudWatch logs; this PR adds a role with the correct access rights. Adding it to the existing cloudtrail module means that it will be automatically picked up by all the accounts.
It has been configured so that the role in each account can be assumed by the main account; this is so that we can validate the logs periodically with Jenkins.

Add role for validating CloudWatch logs

---

terraform/accounts/backups/cloudwatch.tf

Backups account never had a digitalmarketplaces log group, so we don't
want to create one now

digitalmarketplace not digitalmarketplaces

---

Makefile
scripts/add-ip-whitelist-route-service.sh
vars/ip_whitelist_routes.json

Add APPLICATION_NAME arg to ip-whitelist script so script only adds route relevant to current deployment
This script may cause failures when routes do not yet exist. So if a new route is added to the vars here for whitelisting, and this script runs without the route existing already, we will see deployment failures.
* Add new variable to script
* Supply new var in Makefile
* Nest values in json by app name

NOTICKET-make-ip-whitelist-script-more-robust

---

Makefile

We install tools such as yq that are expected by our deploy scripts.
This commit adds a line to the Makefile that adds the virtualenv to the
PATH of Makefile recipes so that scripts will be able to use these
commands.

Fix deploy scripts

---

vars/common.yml
vars/ip_whitelist_routes.json
vars/production.yml

~This would allow https://github.com/alphagov/digitalmarketplace-router/pull/64 to be implemented in a slightly neater way.~
To enable https://trello.com/c/wkDN6HHk

paas manifests: hook up /_metrics route for router

---

vars/production.yml

G-Cloud 11 has gone into standstill, we should increase our capacity
precautionarily.

Increase instances for supplier frontend and antivirus api

---

terraform/modules/jenkins/jenkins/ec2.tf

We encrypted our data volume in the AWS console but did not add that to
our terraform, this commit fixes that.

Ensure new Jenkins volumes are encrypted

---

scripts/import-and-clean-db-dump.sh
terraform/accounts/main/jenkins.tf
terraform/modules/jenkins/jenkins/ec2.tf

* Clarify that `aws_key_pair.jenkins.key_name` and `var.ssh_key_name` are the same thing
* Remove provider block from within jenkins module  …
* Provider blocks should be inherited from parent module (accounts/main)
* https://www.terraform.io/docs/configuration/modules.html#providers-within-modules
> While in principle provider blocks can appear in any module, it is recommended that they be placed only in the root module of a configuration, since this approach allows users to configure providers just once and re-use them across all descendent modules.

448 run jenkins on u1804 2

---

terraform/environments/production/alarms.tf
terraform/modules/logging/alarms/reset-email-bad-role/alarms.tf
terraform/modules/logging/alarms/reset-email-bad-role/variables.tf
terraform/modules/logging/log-metric-filters/main.tf

https://trello.com/c/Vxmq7W0m
Seems to work.
Alarm is only enabled for production, because I don't think it's a particular worry for other environments, where we can still view the metric from the aws console for testing & debugging purposes.

add log metric and alarm for login.reset-email.bad-role

---

vars/production.yml

production paas instances: scale supplier-frontend and api down to 8 instances each post-DOS4-closure

---

Makefile

## Add health-check-http-endpoint none when creating db migration app
Recieved error:
Health check type must be 'http' to set a health check HTTP endpoint.
Assumption is that we cannot set health-check-http-endpoint endpoint value when setting health-check-type to none. Command line arguments override manifest values so this should solve the problem.
https://trello.com/c/IgxiQyEE/1071-why-did-api-release-to-preview-fail

1071-why-did-api-release-to-preview-fail

---

Makefile
paas/db-backup.j2
paas/db-migration.j2
vars/common.yml

Create new manifest for a no-route app with db access to perform db-migration
Instead of using the api app manifest to perform migrations we can use a separate manifest that only gives the migrations app what it needs.
This removes the need to override loads of manifest values in the call to cf push which caused the below error
https://trello.com/c/IgxiQyEE/1071-why-did-api-release-to-preview-fail

1071-why-did-api-release-to-preview-fail-2

---

terraform/environments/preview/alarms.tf

We've decided we don't want this on preview.
We want to be able to test the pw reset for the admin-manager but don't want an alert every time.
https://trello.com/c/LyeA2teJ/1094-turn-off-amding-manager-pw-change-alarm-on-preview
https://trello.com/c/RIVAv5gM/1018-admin-manager-can-reset-their-own-password-once-logged-in-and-its-triggering-the-new-alarm

1094-turn-off-admin-manager-pw-change-alarm-on-preview

---

terraform/environments/preview/alarms.tf
terraform/environments/production/alarms.tf

Add alarm to trigger when lambda fails with an error.
On the 4th of October logit is going to roll over an intermediate certificate. We want an alert to capture this and similar issues
https://trello.com/c/tsArQ9k3/1098-kibana-alarm-on-failure-of-log-shipping-lambda

1098-kibana-alarm-on-failure-of-log-shipping-lambda

---

dmaws/utils.py
scripts/generate-paas-manifest.py
tests/test_utils.py

The jinja templates are solely used for paas manifest configuration. We're not sure what the impact of autoescaping will be, either now or in the future, and so we've taken a positive decision to turn it off.
I've also moved an unused import away from `utils.py`, where it's not used, to the two places it *is* used - `test_utils` and `generate-paas-manifest.py`
[Ticket](https://trello.com/c/H2ubPYqz/306-enable-autoescape-on-jinja-templates)

Disable autoescape for jinja templates

---

terraform/accounts/main/codecommit.tf

We want to be able to backup the digitalmarketplace-govuk-frontend
repository to AWS CodeCommit, so we need to add it to the list of repos
here.
We add it to the end because otherwise Terraform will try to recreate
all the resources for repositories that follow in the list if we insert
in the correct alphabetical location.
https://trello.com/c/KBZFQOfK/326-create-a-new-digitalmarketplace-shared-frontend-code-repo

Add digitalmarketplace-gov-uk to CodeCommit

---

vars/preview.yml

https://trello.com/c/7IanBWbi/1234-search-api-on-preview-bump-memory
Overnight indexing failures on Preview add quite a bit of noise to the release channel. Usually the Preview `search-api` app has run out of memory. 
The Staging `search-api` is also on 512Mb, but has 2 instances instead of 1 (Production is on 512Mb as well, with 5 instances). 
I was originally going to bump the memory up to 2GB as per the `api` and `antivirus-api`, but I decided to reflect 'reality' as closely as possible by bumping the number of Preview instances instead.

Bump Search API app to 2 instances on preview

---

paas/antivirus-api.j2

trello: https://trello.com/c/JDKeSdiu/1245-increase-antivirus-apis-manifest-startup-timeout-setting
The timeout is also limited by the could controller's maximum_health_check_timeout which is 180 by default.

increase antivirus timeout at startup from 60 to 90 seconds

---

terraform/accounts/development/main.tf
terraform/accounts/development/variables.tf
terraform/accounts/main/jenkins.tf
terraform/accounts/main/main.tf
terraform/accounts/main/variables.tf
terraform/accounts/production/main.tf
terraform/accounts/production/variables.tf
terraform/modules/iam-common/common_policies.tf
terraform/modules/iam-common/variables.tf
terraform/modules/jenkins/jenkins/security_group.tf
terraform/modules/jenkins/jenkins/variables.tf

Update to new variable name used in credentials
https://trello.com/c/9k6TWovP/1145-remove-adminuserips-and-userips-from-creds-terraform-commonjson-and-rename-devuserips
Changed dev_user_ips to aws_account_and_jenkins_login_ips to better reflect use case
Requires:
https://github.com/alphagov/digitalmarketplace-credentials/pull/274

1145-remove-adminuserips-and-userips-from-creds-terraform-commonjson-and-rename-devuserips

---

.travis.yml
requirements-dev.txt
requirements.txt

https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- No dependency bumps so far 🤞

Enable Travis checks for Python 3.7 and 3.8

---

Makefile

Ticket: https://trello.com/c/VBYabYVZ/1436-db-restore-on-staging-failed
Our clean_and_apply_db_dump job on Jenkins has stopped working because the postgres Docker image expects an environment variable POSTGRES_PASSWORD.
This commit tells `docker run` to pass the environment variable on to the container; we leave it up to the entity running the Makefile to choose the password.

Add postgres password envvar to postgres container

---

vars/production.yml

- We had more crashes of buyerFE and searchAPI, despite the traffic hasn’t really been ramping up. So it seems the strategy of scaling up servers is not very effective (at least for those apps). Let’s try scaling out.
- See https://trello.com/c/cfMyItQs and https://docs.google.com/document/d/1BLoJY0cpyNLVEKRFNjw98chTtMcbEEOAQmWhC7bmHWk/edit#heading=h.awi1p9ezj2mx
Signed-off-by: Paula Valenca <paula.valenca@digital.cabinet-office.gov.uk>

Scale app servers for G12

---

vars/preview.yml

https://trello.com/c/NdmLe2dd/1551-monitor-preview-buyer-fe-flakiness
Following recent app flakiness during smoulder tests. 
For example, at 2020-03-23T20:50:07Z  the Preview Buyer FE instance recycled itself (without crashing), during a smoulder test run. Although it recovered, this triggered some failures and noise in our release channel.
The Search API and router already have 2 instances, other Preview apps all have 1.

Scale Preview Buyer FE to 2 instances

---

Makefile

https://trello.com/c/m5NtK9z3/1711-re-rerun-production-backup-job
This failed with `OUT Exit status 137 (out of memory)` 
Bumping to 5G memory and disk to give us some headroom.

bump db-backup memory and disk to 5G

---

terraform/accounts/main/alarms.tf
terraform/environments/preview/alarms.tf
terraform/environments/production/alarms.tf
terraform/modules/logging/alarms/admin-manager-password-reset/alarms.tf
terraform/modules/logging/alarms/dropped-av-sns/alarms.tf
terraform/modules/logging/alarms/missing-logs/alarms.tf
terraform/modules/logging/alarms/reset-email-bad-role/alarms.tf
terraform/modules/logging/alarms/slow-requests/alarms.tf
terraform/modules/logging/alarms/status-code/alarms.tf

~~**DO NOT MERGE OR APPLY BEFORE #675**~~ READY TO MERGE
Trello: https://trello.com/c/fF0V5auU
Please check commit messages for more information.
Note there are two actions that should follow after this PR has been merged:

Increase time window for all alerts to 5 minutes

---

db-backup/create-db-dump.sh

https://trello.com/c/TNoXg0lb/147-2-postgres-secrets-logged-to-console-when-db-backup-job-fails
The effect of the `set -x` argument was to print and expand all arguments which caused the printing of secrets into the logs.
Please documentation at: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
This also switches to use the PaaS built-in [DATABASE_URL](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#DATABASE-URL) rather than parsing VCAP using jq.
You can see the output of this branch for a failure case here: https://ci.marketplace.team/job/database-backup/1166/execution/node/161/log/

do not expand console output

---

vars/common.yml
vars/preview.yml

https://trello.com/c/yJeKtmkj/201-2-setup-splunk-on-our-apps-for-log-aggregation-timebox-2-days
add splunk service to apps. This is as-per https://github.com/alphagov/tech-ops/blob/master/cyber-security/components/csls-splunk-broker/docs/user-guide.md#bind-a-splunk-service-to-your-apps-using-an-app-manifest

add splunk service to apps

---

vars/preview.yml

User frontend needs to be bound to Splunk, not Elasticsearch.

Fix typo in preview services

---

terraform/environments/preview/main.tf
terraform/environments/production/main.tf
terraform/environments/staging/main.tf
terraform/modules/router/route53.tf
terraform/modules/router/variables.tf

https://trello.com/c/40xHkNW8/1733-2-update-paas-cdn
This terraforms the validation changes from Let's Encrypt to ACM. The Preview and Staging environment changes have already been applied, once this is merged we will apply the production changes.
---------------
Here is the corresponding PaaS change request for reference: 
```
Create the following CNAME records to direct traffic from your domains to your CDN route
www.digitalmarketplace.service.gov.uk => d3pp9vxqezcjw2.cloudfront.net
api.digitalmarketplace.service.gov.uk =>
d3pp9vxqezcjw2.cloudfront.net
search-api.digitalmarketplace.service.gov.uk => d3pp9vxqezcjw2.cloudfront.net
antivirus-api.digitalmarketplace.service.gov.uk => d3pp9vxqezcjw2.cloudfront.net
assets.digitalmarketplace.service.gov.uk =>
d3pp9vxqezcjw2.cloudfront.net
To …
```

terraform ACM certificate validation records

---

vars/production.yml

Reverts alphagov/digitalmarketplace-aws#704
scaling back down after anticipated increase in traffic.

Revert "increase supplier frontend instances and memory"

---

Makefile

Allow the `cf logout` command to fail by using Make specific syntax[[1]]. If for some reason we aren't already logged in to PaaS, cf logout will complain that it can't log out. I think this caused some recent release failures.
https://ci.marketplace.team/job/release-app-paas/7084/console
[1]: https://www.gnu.org/software/make/manual/html_node/Errors.html#Errors

Fix bug in paas-clean

---

terraform/environments/preview/main.tf

This is needed before setting G-Cloud-12 as live in preview for testing.
Following the procedure in https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/framework-lifecycle-for-developers.html#g-cloud

Disconnect AV from the docs bucket in preview

---

terraform/environments/preview/main.tf

The purpose of the disconnection was to allow us to publish the framework in preview without overloading the AV. However, it turns out that this is blocked because preview doesn't have all the submission documents that production does. This causes the publish script to fail.
Copying the documents from production to preview is hard (94GB). So instead of publishing the framework in preview, we're just going to do it in production instead. The database sync will then propagate the publishing to preview. Thus, we no longer need to run the script, so can re-enable AV.
Reverts alphagov/digitalmarketplace-aws#732

Revert "Disconnect AV from the docs bucket in preview"

---

.secrets.baseline
terraform/README.md

We're currently using v0.11.x, which is rather old. tfenv is probably the best way of managing multiple terraform versions.

Recommend using tfenv to install terraform

---

Makefile

https://trello.com/c/Kop14JBa/1425-spike-our-zero-downtime-deploy-script-can-fail-in-a-way-that-requires-manual-recovery
Allow the commands to delete the previous app in the deploy-app recipe to fail [[1]]. If for some reason the existing app has the wrong name or isn't present, we still want the deployed app to be renamed to have the right name.
[1]: https://www.gnu.org/software/make/manual/html_node/Errors.html#Errors

Fix bug in deploy-app recipe

---

Makefile

https://trello.com/c/kbhJdTm3/567-remove-flaskscript-from-dmutils
We are deprecating the use of `python application.py ...`, we should use`flask ...` instead.
I have tested this locally running against preview.

Remove Flask-Script

---

Makefile

https://trello.com/c/TM0mwfiE/2014-add-dockerhub-credentials-to-paas-manifests
Note `CF_DOCKER_PASSWORD` should be automatically picked up and used as long as the env var is set. See https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#private-repo

Use Docker credentials

---

vars/staging.yml

Trello: https://trello.com/c/kGmsXWZ1/520-3-find-out-whether-dmp-can-cope-with-dos5-closing
We will shortly be running load testing on staging. The goal is to find out whether the DMp is likely to be able to handle a reasonable worst-case scenario for traffic during DOS 5 closing.
For this test to give us meaningful results, we need staging to match production as it will be on the day of DOS 5 closing. Thus, scale up staging. I've modelled the scale after that we used for DOS 5 opening and G12 closing.
Also disable rate-limiting, since we are running the load test from a single IP.

Scale up staging for load testing

---

README.md

We need to run a Jenkins job, which isn't immediately obvious. Add a link to the relevant manual page.

Add link to PaaS (re-) release process

---

vars/staging.yml

Trello: https://trello.com/c/kGmsXWZ1/520-3-find-out-whether-dmp-can-cope-with-dos5-closing
The load test we ran today was broadly successful. We found though that antivirus-api seemed to be struggling a bit. This isn't actually a problem - the overnight job will pick up anything that it missed during the day.
Double the number of instances ahead of our test tomorrow to see if that helps things.
Will be reverted tomorrow after the load testing is complete.

Double antivirus-api instances for load tests

---

vars/staging.yml

Trello: https://trello.com/c/kGmsXWZ1/520-3-find-out-whether-dmp-can-cope-with-dos5-closing
We've now finished the load testing, so we can scale staging back in.
Reverts https://github.com/alphagov/digitalmarketplace-aws/pull/760 and https://github.com/alphagov/digitalmarketplace-aws/pull/758

Scale staging back to its normal size

---

vars/preview.yml

https://trello.com/c/0XO8CHaP/381-05-stand-up-the-paas-infrastructure-for-the-preview-environment
Bind frontend apps to redis instance for testing on preview only 
(note the other services need to be specified so they are not overwritten)﻿

bind apps to redis on preview

---

paas/admin-frontend.j2
paas/brief-responses-frontend.j2
paas/briefs-frontend.j2
paas/buyer-frontend.j2
paas/supplier-frontend.j2
paas/user-frontend.j2

https://trello.com/c/0XO8CHaP/381-05-stand-up-the-paas-infrastructure-for-the-preview-environment
The code in https://github.com/alphagov/digitalmarketplace-utils/pull/584 expects this env var to be set, this is a prerequisite to enabling redis sessions on preview.

set redis service name on frontend apps

---

paas/supplier-frontend.j2

https://trello.com/c/NcLdEdYq/2082-incident-db-api-contract-has-expired
we can revert this now credentials are working again.
Reverts alphagov/digitalmarketplace-aws#767

Revert "temporarily remove vars"

---

paas/_base.j2
vars/preview.yml

https://trello.com/c/0XO8CHaP/381-05-stand-up-the-paas-infrastructure-for-the-preview-environment
We want to test redis initially on preview only. This is behind an env var. To set this on preview only this also introduces some logic to allow per-environment additions to the env block of the manifest.
I have tested this using `make generate-manifest`

enable redis env var on preview only

---

paas/_base.j2
vars/preview.yml

Revert whilst investigating why this broke deployment.
Reverts alphagov/digitalmarketplace-aws#769

Revert "enable redis env var on preview only"

---

paas/_base.j2
vars/preview.yml

Re-enabling this now we have deployed an attempted fix.
Reverts alphagov/digitalmarketplace-aws#770

re-enable redis env var on preview

---

paas/_base.j2
vars/preview.yml

Revert this so we don't continue blocking the pipeline.
Reverts alphagov/digitalmarketplace-aws#771

Revert "re-enable redis env var on preview"

---

vars/production.yml

DOS5 closes for applications at 1pm GMT November 17th. Scale the production environment up so we can handle the expected additional traffic. Decisions explained in the relevant [DRD](https://docs.google.com/document/d/18aKH60ojA0IVWjtAiLmxNRxcTeGnwWCofOAVn21Q0mM/) (GDS only)
https://trello.com/c/H2BFCt6l/535-05-scale-platform-manually-for-dos5

Scale up production for DOS5 closing

---

vars/production.yml

Trello: https://trello.com/c/guiQfAf8/1456-our-request-rate-limit-varies-depending-on-the-number-of-router-apps-deployed
nginx does rate limiting on a per-instance basis. So if you increase the number of instances, you need to decrease the rte limit so that the overall rate limit stays the same. Add a comment reminding people to do this.
The same thing could also apply for other environments, but we only really care about production.

Document need to update production rate limit

---

vars/production.yml

DOS5 has successfully closed and traffic on the site looks sensible this afternoon. We can scale back down.
Reverts alphagov/digitalmarketplace-aws#777
https://trello.com/c/qyafLfJW/550-05-scale-back-down-after-dos5-closes

Revert "Scale up production for DOS5 closing"

---

vars/staging.yml

Reverts alphagov/digitalmarketplace-aws#781
https://trello.com/c/2qF5k1Xx/570-1-run-performance-tests-against-staging-for-the-new-user-session-management-tbc
We can re-enable rate limiting now we've concluded performance tests.

Revert "temporarily disable rate limiting"

---

terraform/accounts/main/alarms.tf

This was changed in the AWS console by @bjgill as part of
https://trello.com/c/tlhoS1vi/2088-disk-space-alarms-for-jenkins-are-reporting-incorrect-values
Update the config in Terraform as well so we don't revert the changes when making future infrastructure changes. I added the `datapoints_to_alarm` variable because Terraform was complaining without it and we do want to alarm when we get 1 datapoint:
```
Error: aws_cloudwatch_metric_alarm.jenkins_data_volume_disk_space: expected datapoints_to_alarm to be at least (1), got 0
```

Change Jenkins disk space alarms to use Minimum

---

paas/api.j2
paas/supplier-frontend.j2

Trello: https://trello.com/c/KikQx3R2/
We will be using this configuration to show the G12 recovery process only to the suppliers involved.
Environment variables must be strings, so convert the list to a comma-separated string.
This relies on https://github.com/alphagov/digitalmarketplace-credentials/pull/359, which adds the necessary fields into the credentials.

Pass list of suppliers to apps

---

terraform/accounts/main/jenkins.tf
terraform/modules/iam-users/users/main.tf

https://trello.com/c/xtHL9yV1/603-1-clean-up-after-pentesting
The ITHC company has finished their work so we can remove their IAM account and the Jenkins instance we stood up for them to test against.
The `SecurityAudit` group and roles are still in place for next year - I will find somewhere suitable to document these to save us time in the future.

Remove ITHC IAM user and Jenkins instance

---

db-backup/Dockerfile
db-backup/upload-dump-to-s3.py

use `curl` to perform backup upload to workaround python error
https://trello.com/c/dG5psGPK/2070-production-database-backup-failing
* This will need to be manually pushed to the Docker tag once merged, I have run it against a tag and you can see that output on Jenkins here: https://ci.marketplace.team/job/database-backup/
* I have made a separate card to address the issues around the other image dependencies being very out of date which is here https://trello.com/c/mZ1ZDfS1 this is a known issue as described in: https://alphagov.github.io/digitalmarketplace-manual/developing-the-digital-marketplace/docker-strategies.html#manually-managed

use curl to perform backup upload

---

vars/common.yml

We can remove this as it is now enabled by default.

remove redis env var

---

vars/common.yml
vars/ip_whitelist_routes.json
vars/production.yml

This reverts commit 1f63c17bb66fbd75fefdb26a14f9a8db806f9158.
We have found that we don't use the metrics from nginx ever, and the metrics exporter often causes a lot of alarms because it doesn't start reliably.
@gidsg and I agreed that we should just remove the metrics.
Once this PR has been merged and the router has been redeployed on all stages we can merge alphagov/digitalmarketplace-router#98.

Remove router prometheus metrics

---

Makefile
db-backup/Dockerfile

We are now using PostgreSQL 10.13 in production, we should make sure our database backup pipeline uses the same or newer version.
I have verfied that the Docker images involved exist and can be built, once this PR is approved I will push `digitalmarketplace/db-backup` to Docker Hub.

Update postgresql in `make run-postgres-container` from 9.5 to 10.13

---

paas/supplier-frontend.j2

Trello: https://trello.com/c/13Ryt5o5/679-5-as-a-supplier-i-cannot-see-submit-any-draft-services-that-ccs-will-not-consider
We will be using this configuration to hide draft services not involved in the G12 recovery process.
Environment variables must be strings, so convert the list to a comma-separated string.
This relies on https://github.com/alphagov/digitalmarketplace-credentials/pull/366, which adds the necessary fields into the credentials.

Pass list of draft services to supplier-frontend

---

.github/workflows/test.yml
Makefile
scripts/check-terraform-formatting.sh
scripts/validate-terraform.sh
terraform/accounts/main/alarms.tf
terraform/accounts/production/main.tf
terraform/environments/preview/alarms.tf

Inspired by [a recent PR](https://github.com/alphagov/digitalmarketplace-aws/pull/750), where we wasted a lot of time on manual testing.
Add a script that we run in CI. This will check that our terraform code is syntactically correct, internally consistent, and properly formatted. It does not try to access external state, so is safe to run in CI.
Needs Terraform 0.12, so this PR depends on https://github.com/alphagov/digitalmarketplace-aws/pull/750

Add terraform testing to CI

---

Makefile

The upgrade to postgres 12 failed. So, until that's fixed, we're back on postgres 10.
Reverts alphagov/digitalmarketplace-aws#827

Revert "bump postgres container version"

---

Makefile
db-backup/Dockerfile

https://trello.com/c/mZ1ZDfS1/791-3-db-backup-app-is-running-end-of-life-os
Updates container and client to use postgres 12. Have tested successfully against preview: https://ci.marketplace.team/job/database-backup/1393/
* `postgresql-client-12` is not available in the default package repository, therefore this adds the postgres repository as per the guidance in: https://www.postgresql.org/download/linux/ubuntu/
* This should not be merged until Postgres 12 has been rolled out to all environments 
* I will push the docker image once this PR is merged

Upgrade backup task for postgres 12

---

terraform/accounts/main/codecommit.tf

We've started to change our default git branches from `master` to `main`. Update our Terraform configuration to be able to handle different default branch names, and update the branch names for the repos we've already changed.
Also switch to the new (in 0.12.6) `for_each` Terraform operator which makes things a bit easier.
Applying these changes will destroy and re-create all of our CodeCommit resources because they're currently saved in the Terraform state by list index, and this PR changes each repo to a map key. I have checked the Jenkins job which does the backup and I don't think this will cause problems, but I'll run the job after applying to make sure.
I'll also add an item to the 'Tasks per-repo' check list on the attached Trello card to remind us to also update this file with the …

Update CodeCommit repository default branches

---

terraform/accounts/main/codecommit.tf

We recently created a new repo - [digitalmarketplace-developer-tools](https://github.com/alphagov/digitalmarketplace-developer-tools)
Add this repo to our CodeCommit backups so we have a copy in case something disastrous happens to Github.

Add digitalmarketplace-developer-tools to CodeCommit backups

---

.github/workflows/test.yml

We don't use lxml in this repo so we don't need to install its build dependencies.

Remove unneeded Ubuntu dependencies

---

terraform/modules/iam-users/users/main.tf

Louise stayed with GDS and so is no longer our Lead TA. We've already removed them from the groups allowing access to anything in https://github.com/alphagov/digitalmarketplace-credentials/pull/369 so it's safe to also remove the AWS account.
https://trello.com/c/i0mmpFna/885-1-address-ithc-issue-649-credentials-unused-for-90-days-or-greater-are-not-disabled

Remove 'louiseryan' AWS user

---

Makefile
terraform/accounts/backups/main.tf
terraform/accounts/backups/s3_buckets.tf
terraform/accounts/development/main.tf
terraform/accounts/main/main.tf
terraform/accounts/main/route53.tf
terraform/accounts/production/main.tf
terraform/environments/preview/main.tf
terraform/environments/preview/s3_replication_buckets.tf
terraform/environments/production/main.tf
terraform/environments/production/s3_replication_buckets.tf
terraform/environments/staging/main.tf
terraform/modules/antivirus-sns/main.tf
terraform/modules/cloudtrail/main.tf
terraform/modules/iam-common/main.tf
terraform/modules/jenkins/jenkins/ec2.tf
terraform/modules/jenkins/log_bucket/s3_bucket.tf
terraform/modules/jenkins/snapshots/snapshots.tf
terraform/modules/log-groups/main.tf
terraform/modules/log-streaming/lambda.tf
terraform/modules/logging/log-metric-filters/main.tf
terraform/modules/paas/iam.tf
terraform/modules/router/route53.tf
terraform/modules/sops-credentials/main.tf
terraform/modules/switch-roles/developers.tf

Apologies in advance, this is a sizeable PR but it's not easy to split up.
In order to use the Node 14 Lambda runtime instead of Node 10 for our log streaming Lambda[[1]], we also need to upgrade the AWS provider.
Some of our modules had provider versions defined and some didn't, so I've taken the opportunity to clean things up and only define provider versions in the places we can run Terraform from - `main.tf` in each account and environment folder. The modules will get the correct version of the provider passed down to them when they're loaded.
We are on Terraform v.0.12, but plan to upgrade to 0.13 and 0.14 soon. Use the new `required_providers` syntax for the version definitions so this change is compatible with both Terraform v0.12 and v0.13[[2]].
Also set a `AWS_DEFAULT_REGION` …

Upgrade Terraform AWS provider to v3.34.0

---

terraform/modules/cloudtrail/modules/cloudtrail-cloudtrail/main.tf
terraform/modules/cloudtrail/modules/cloudtrail-cloudwatch/main.tf

In #874 we upgraded the Terraform AWS provider to 3.34.0. In the PR description, I noted that this upgrade made changes to the CloudWatch log group ARN, but that I didn't think it mattered.
It turns out this isn't true - AWS rejects the ARN without a trailing `:*` but this only raises an error when we try to apply the changes.
From the provider upgrade docs[[1]]:
> Previously, the resource returned the Amazon Resource Name (ARN) directly from the API, which included a :* suffix to denote all CloudWatch Log Streams under the CloudWatch Log Group. Most other AWS resources that return ARNs and many other AWS services do not use the :* suffix. The suffix is now automatically removed.
The docs recommend using string interpolation to add the trailing `:*` back in everywhere it was missing, so …

Fix CloudWatch log group ARN

---

terraform/modules/log-streaming/lambda.tf

Node 10 is EOL on April 30th 2021 and will no longer receive security updates. Upgrade the runtime to Node 14, the most recent LTS version which is supported until April 2023.
I have had a quick scan of [the changelogs](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md) from Node 10 to 14 and I don't believe we are using anything that's been deprecated. I'll deploy to preview first and check logs are still arriving in Logit to make sure it's all still fine before doing the other environments.
https://trello.com/c/sBqxdTZC/1734-upgrade-logstream-lambda-to-latest-active-lts

Upgrade log streaming Lambda runtime from Node 10 to Node 14

---

terraform/modules/iam-users/users/main.tf

He's no longer working at CDIO
Should be deployed along with https://github.com/alphagov/digitalmarketplace-credentials/pull/379
to avoid AWS complaining about members of groups who don't exist.
https://trello.com/c/lWn7rC35/2185-remove-ares-from-all-the-things-%F0%9F%91%8B

Remove Ares' AWS account

---

.github/workflows/test.yml

`tfenv` has stopped installing via `brew` on Linux, seemingly due to an issue in the dependency chain breaking the build e.g. https://github.com/alphagov/digitalmarketplace-aws/runs/2325307890?check_suite_focus=true
```
Run brew install tfenv
==> Downloading https://linuxbrew.bintray.com/bottles/bzip2-1.0.8.x86_64_linux.bottle.1.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "bzip2"
Download failed: https://linuxbrew.bintray.com/bottles/bzip2-1.0.8.x86_64_linux.bottle.1.tar.gz
Error: Process completed with exit code 1.
```
to work around this we can install tfenv manually, this is as per the manual steps https://github.com/tfutils/tfenv#manual adapted slightly to work with Github Actions.
(spotted whilst working on another story)

install tfenv manually

---

vars/preview.yml
vars/staging.yml

Trello: https://trello.com/c/wW4w1XQZ
We need to decrease the production rate limit to cope with an over-eager scraper. See https://github.com/alphagov/digitalmarketplace-router/pull/109
Unfortunately, this lower rate limit is just too low for Preview and Staging. They typically see peaks of ~8 requests/s from our tests. The rate limit change reduces their rate limits from 10 requests/s to 6 requests/s.
So increase the number of router instances to 3. This should increase the rate limit for those environments to 9 requests/s, which should be sufficient for our tests.
This is intended to be a temporary stop-gap whilst we work out a better long-term approach to coping with the scraper's traffic.

Add another router app to Staging and Preview

---

terraform/accounts/main/alarms.tf

To every minute, rather than every 5 minutes.
We recently had an incident where Docker used up all the available disk space building multiple images concurrently, crashed and then deleted the temporary files that had caused the problem. This wasn't caught by the disk space alarm because it only checks every 5 minutes and the disk filled up much faster than that.
The AWS docs say that events from AWS services are at a 1 minute frequency by default[[1]], so the highest frequency we can set the alarm to is also 1 minute.
https://trello.com/c/LkA70qqT/812-1-investigate-why-we-didnt-get-a-jenkins-low-disk-space-alert
[1]: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html

Increase frequency of Jenkins disk space checks

---

terraform/accounts/backups/main.tf
terraform/accounts/development/main.tf
terraform/accounts/main/main.tf
terraform/accounts/production/main.tf

Define access policies for our Terraform state buckets that only permit encrypted connections. This addresses a medium-risk vulnerability from our recent ITHC.
These are the Terraform state buckets and therefore they cannot be created through Terraform or easily managed through a module. This is why the policies are defined in-line after the Terraform backend configuration in each AWS account.
https://trello.com/c/KeWS6zRV/925-644-bucket-allowing-clear-text-http-communication

Only allow encrypted connections to Terraform state buckets

---

vars/staging.yml

https://trello.com/c/c00Ix4wd/2230-p4-database-dump-failing-on-staging
Reverts alphagov/digitalmarketplace-aws#914
Revert to use renamed restored DB.

Revert "use restored DB"

---

terraform/accounts/main/codecommit.tf

to `main` as this is now what we're using. This will fix the failing code backup job.
https://trello.com/c/DrVWMkcZ/2169-rename-default-branches-on-our-repos-from-master-to-main.

Change `digitalmarketplace-content-loader` default branch

---

terraform/accounts/backups/main.tf
terraform/accounts/backups/s3_buckets.tf
terraform/accounts/development/main.tf
terraform/accounts/development/s3_buckets.tf
terraform/accounts/main/main.tf
terraform/accounts/production/main.tf
terraform/environments/preview/s3_buckets.tf
terraform/environments/preview/s3_replication_buckets.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/production/s3_replication_buckets.tf
terraform/environments/staging/s3_buckets.tf
terraform/modules/cloudtrail/modules/cloudtrail-bucket/main.tf
terraform/modules/jenkins/log_bucket/s3_bucket.tf
terraform/modules/s3-document-bucket/main.tf

https://trello.com/c/HCf26VVT/922-3-645-bucket-without-default-encryption-enabled
Enable default encryption for all our S3 buckets. This was prompted by the recent IT health check. Security benefits likely to be minimal, but it's free and easy to enable, so why not.
We've tested that this shouldn't cause problems already - see 029e9ac. This commit adds the necessary config to all other buckets in all environments/accounts/etc.
Also terraformat picked up some unrelated formatting-only changes.

Enable default S3 encryption

---

paas/buyer-frontend.j2

https://trello.com/c/5E22SHaQ/988-ccs-sourcing-admins-cant-view-suppliers-modern-slavery-statements
It's currently hard-coded (https://github.com/alphagov/digitalmarketplace-buyer-frontend/commit/1e5b9e7def105d4c055b25c72fa7e6fd2acd49e6), which we want to remove.

Add assets URL to buyer frontend

---

terraform/environments/preview/alarms.tf
terraform/environments/production/alarms.tf
terraform/modules/logging/alarms/slow-requests/alarms.tf

We have a scraper which is triggering these alarms with 100's of requests every hour. We don't need to do anything when they're triggered so they're causing us unnecessary alarm fatigue and could result in us missing real problems. 
Increasing the trigger thresholds to over what the scraper causes will effectively cause the alarms to never trigger, which won't be any more use than simply deleting them. 
https://trello.com/c/sZqatZVp/4-2-reduce-alerts-that-require-no-action

Remove alarms that require no action

---

terraform/environments/preview/s3_buckets.tf
terraform/environments/preview/s3_replication_buckets.tf
terraform/environments/production/s3_buckets.tf
terraform/environments/production/s3_replication_buckets.tf
terraform/environments/staging/s3_buckets.tf
terraform/modules/s3-document-bucket/main.tf

This was identified in our recent ITHC and we've already updated all the buckets in the AWS console. Update Terraform to match what's deployed.
If you checkout this branch and run `make plan` for one of preview, staging or production the only changes you should now see are removing some Cloudwatch alarms (see #941) and maybe a DNS validation update.

Enable MFA delete protection on our S3 buckets

---

db-backup/Dockerfile

https://trello.com/c/PqMIVIGW/33-upgrade-apps-to-python-36-39
Note I have tested this using a tag on Jenkins and Dockerhub 
https://ci.marketplace.team/job/database-backup/1522/
https://hub.docker.com/layers/digitalmarketplace/db-backup/db-backup-python-39/images/sha256-8483a4c2127a2205acb0993aa051d3a89054f4f06c2776ee69d389f05e731ddf?context=repo
As this is manually managed, once this is merged I will push it to the `latest` tag.

use python 3.9 in backup job dockerfile

---

terraform/accounts/main/jenkins.tf
terraform/modules/jenkins/jenkins/ec2.tf

https://trello.com/c/cacoWXHC/63-5-upgrade-the-version-of-python-on-jenkins-to-at-least-38
This sets up a new Jenkins instance which is running Ubuntu 20 LTS which includes Python 3.8 in the package manager.

Set up Ubuntu 20 LTS instance

---

terraform/accounts/main/jenkins.tf

https://trello.com/c/cacoWXHC/63-5-upgrade-the-version-of-python-on-jenkins-to-at-least-38
We have retired this in favour of jenkins3.

remove old jenkins instance

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/NmHLg0q7/92-2-onboard-two-ccs-techops-people-so-they-can-pair-with-us
From CCS techops. Have confirmed we've OK to give George prod access - see linked ticket for details.
https://github.com/alphagov/digitalmarketplace-credentials/pull/404 is the associated credentials PR

Add George Hill

---

vars/staging.yml

The last time staging was updated with clean live-like data, the job failed and left the database in an inconsistent state, so we had to do a restore (see https://alphagov.github.io/digitalmarketplace-manual/infrastructure/database-backups.html?highlight=database%20restore#restoring-from-a-backup)
Trello: https://trello.com/c/VmiVQKkA

Point API to new restored database in Staging

---

vars/staging.yml

Renaming new service to digitalmarketplace_api_db (see https://alphagov.github.io/digitalmarketplace-manual/infrastructure/database-backups.html?highlight=database%20restore#restoring-from-a-backup)
This reverts commit 9d0c3512

Revert "Point API to new restored database in Staging"

---

requirements.txt

Dependabot can't handle this properly because both boto3 and awscli depend on botocore (see https://github.com/Crown-Commercial-Service/digitalmarketplace-aws/pull/1009). Update to the latest version of both, which both depend on the same version of botocore.

Update to latest versions of boto3 and awscli

---

terraform/modules/iam-users/users/main.tf

https://trello.com/c/LA87kjkQ/2359-remove-cdio-people-%F0%9F%91%8B
They're part of Cabinet Office CDIO. Since the end of the transition a couple of weeks ago, they are no longer involved with the DMP. So we should remove their access.
To be deployed alongside https://github.com/Crown-Commercial-Service/digitalmarketplace-credentials/pull/446 as part of https://crown-commercial-service.github.io/digitalmarketplace-manual/managing-people-and-secret-things/accounts.html#aws

Remove Paula and Daniele

---

terraform/environments/preview/main.tf
terraform/modules/router/route53.tf

Previously, the ACM DNS entry for assets was using the same name as for www. I think this was a copy-paste error, because there exists an assets_acm_name variable that was defined but not used.
I think this should put a stop to the current dueling between assets and www, where terraform flips back and forth because they both have the same name.

Correct name of ACM validation DNS entry

---

terraform/modules/iam-users/users/main.tf

They were not needed because Techops can switch role from their root account.
Following the process in https://crown-commercial-service.github.io/digitalmarketplace-manual/managing-people-and-secret-things/accounts.html#aws

Remove deleted TechOps logins

---

vars/common.yml

https://trello.com/c/CaH712GG/2443-update-paas-prometheus-exporter
We no longer have it hooked up to anything: it was GDS-specific, so we don't have access in CCS.

Remove digitalmarketplace_prometheus service
